############################################################
# taskserver installation (from source)                    #
# https://taskwarrior.org/docs/taskserver/git.html         #
# https://gothenburgbitfactory.github.io/taskserver-setup/ #
############################################################

# TODO: Perform install / config as a new taskd user
# TODO: Copy _entire_ contents of /tmp/taskserver/pki to /var/taskd
# TODO: Create taskd systemd service
#       (See TASKD.SERVICE slide on
#        https://gothenburgbitfactory.github.io/taskserver-setup/)

- name: Update apt
  shell: apt update
  become: true

- name: Install taskwarrior dependencies
  apt:
    name:
    - git
    - libgnutls30
    - libgnutls28-dev
    - libuuid1
    - uuid-dev
    - cmake
    - make
    - gcc
    - build-essential  # otherwise, cmake complains about CMAKE_CXX_COMPILER being undefined
    - gnutls-bin  # provides certtool
    - net-tools  # provides ifconfig
    state: latest
  become: true

- name: Get taskserver repo
  git:
    repo: https://github.com/GothenburgBitFactory/taskserver.git
    dest: /tmp/taskserver
    version: master

- name: Configure build for taskserver
  shell: 'cmake -DCMAKE_BUILD_TYPE=release .'
  args:
    chdir: /tmp/taskserver

- name: Build taskserver
  shell: make
  args:
    chdir: /tmp/taskserver

- name: Build tests
  shell: make
  args:
    chdir: /tmp/taskserver/test

# Per https://taskwarrior.org/docs/taskserver/git.html
# a few test failures may happen evenn if the build was successful
#
# Ran tests on 1/11/2022 and the only test that failed was
# 'Copyright is current'
- name: Test taskserver build
  shell: ./run_all --verbose > test_results
  args:
    chdir: /tmp/taskserver/test
  ignore_errors: true

- name: Install taskserver
  shell: make install
  args:
    chdir: /tmp/taskserver
  become: true

- name: Verify taskserver is installed
  shell: taskd

##########################################################
# taskserver configuration                               #
# https://taskwarrior.org/docs/taskserver/configure.html #
##########################################################

- name: Create taskd data dir
  file:
    path: /var/taskd
    state: directory
    mode: '0755'
    group: jim
    owner: jim
  become: true

- name: Define TASKDDATA
  lineinfile:
    path: ~/.bashrc
    line: 'export TASKDDATA=/var/taskd'
    regexp: '^export TASKDDATA.*'

- name: Initialize server
  shell: taskd init
  environment:
    TASKDDATA: /var/taskd

- name: Copy over PKI certificate config
  copy:
    src: vars
    dest: /tmp/taskserver/pki/vars
    owner: jim
    group: jim
    mode: '0644'
    force: yes
    backup: yes

# Add /usr/sbin to path so that ifconfig can be found
- name: Generate certificates
  shell: "export PATH=/usr/sbin:$PATH; ./generate"
  args:
    chdir: /tmp/taskserver/pki
  environment:
    TASKDDATA: /var/taskd

- name: Copy over script to install certs
  copy:
    src: install_certs.sh
    dest: /tmp/taskserver/pki/install_certs.sh
    owner: jim
    group: jim
    mode: '0755'

- name: Install certs
  shell: './install_certs.sh'
  args:
    chdir: /tmp/taskserver/pki
  environment:
    TASKDDATA: /var/taskd

- name: Configure logging
  shell: "taskd config --force log /var/taskd/taskd.log"
  args:
    chdir: /tmp/taskserver
  environment:
    TASKDDATA: /var/taskd

- name: Configure pid file
  shell: "taskd config --force pid.file /var/taskd/taskd.pid"
  args:
    chdir: /tmp/taskserver
  environment:
    TASKDDATA: /var/taskd

# Use the _IP ADDRESS_ for the server (not the server name!!)
# otherwise taskd will not accept connections from outside itself
# (https://speakerdeck.com/ddeimeke/taskwarrior-and-taskserver?slide=25)
#
# Based on this post, you can also use 0.0.0.0
# https://superuser.com/questions/1314916/when-listening-to-a-port-taskserver-should-the-local-address-be-localhost-or
# .. so I'll go with that option in case I change the
# local address I'm using for think.
- name: Configure server address
  shell: "taskd config --force server 0.0.0.0:53589"
  args:
    chdir: /tmp/taskserver
  environment:
    TASKDDATA: /var/taskd

######################
# Configure firewall #
######################

# While firewalld is mostly used on RHEL instances,
# Debian can use it, too
# https://computingforgeeks.com/how-to-install-and-configure-firewalld-on-debian/
- name: Install firewalld
  apt:
    name: firewalld
    state: latest
  become: true

# To confirm that a firewall rule has taken effect, run:
# $ sudo firewall-cmd --list-all
#
# To verify that a service is listening on a given port, run:
# $ lsof -i | grep -i listen
#
# To verify you can connect to the taskd server from a remote host, run:
# telnet think 53589
- name: Open port for taskd
  shell: firewall-cmd --permanent --add-port=53589/tcp --zone=public
  become: true

- name: Reload firewalld rules
  shell: firewall-cmd --reload
  become: true

#####################
# Start the server! #
#####################

# To verify that server started, run 'ps -leaf | grep taskd'
# Can also check server status with 'taskdctl status'
- name: Start taskserver
  shell: taskdctl start
  environment:
    TASKDDATA: /var/taskd

# TODO: Make it so that task server automatically restarts

#################################
# Post deployment configuration #
#################################

- name: Create organization
  shell: "taskd add org 'Portladds'"
  environment:
    TASKDDATA: /var/taskd

- name: Create user for Jim (and save key)
  shell: "taskd add user 'Portladds' 'Jim Ladd' > /var/taskd/jim.key"
  environment:
    TASKDDATA: /var/taskd

- name: Create client cert
  shell: "./generate.client portladd_client"
  args:
    chdir: /tmp/taskserver/pki
  environment:
    TASKDDATA: /var/taskd

####################################
# Configuring a taskwarrior client #
####################################
#
# Will need to copy the following to local ~/.task directory
# - portladd_client.cert.pem
# - portladd_client.key.pem
# - ca.cert.pem
#
# Will then need to configure taskwarrior client to use
# these certs:
#
# $ task config taskd.certificate -- ~/.task/portladd_client.cert.pem
# $ task config taskd.key -- ~/.task/portladd_client.key.pem
# $ task config taskd.ca -- ~/.task/ca.cert.pem
#
# Then tell the client the server's address:
# $ task config taskd.server -- think:53589
#
# And, finally, provide your user credentials:
#
# $ task config taskd.credentials -- Portladds/Jim Ladd/<KEY SAVED TO /var/taskd/jim.key>
#
# Your taskwarrior client is now ready to sync!
#
# To sync, run the following (only once! and only on one device!)
# $ task sync init
#
# After the inital sync, you can do a general sync with:
# $ task sync

#############################################
# Configuring the Foreground App on Android #
#############################################
#
# When asked for the server address, you can provide the
# task server's local IP address.
#
# I suppose that if I wanted to sync my todo list
# while away from home I could use a VPN.


###################
# Troubleshooting #
###################
#
# Troubleshooting help is available here:
# https://gothenburgbitfactory.github.io/taskserver-troubleshooting/
