- import_tasks: general.yml
  tags: general_dev_tools

- import_tasks: git.yml
  tags: git

- import_tasks: tmux.yml
  tags: tmux

- import_tasks: bash.yml
  tags: bash

- import_tasks: ag.yml
  tags: ag

- import_tasks: fzf.yml
  tags: fzf

- import_tasks: tech_writing.yml
  tags: tech_writing
