- name: Add ansible project, branch {{ branch }}
  git:
    dest: ~/git/ansible-{{ branch }}
    repo: git@github.com:ansible/ansible.git
    accept_hostkey: yes
  tags: ansible

- name: Get current branch
  shell: git branch | grep '{{ branch }}'
  args:
    chdir: ~/git/ansible-{{ branch }}
  register: git_branch
  failed_when: git_branch.rc > 1
  tags: ansible

- name: Check out branch
  command: git checkout {{ branch }}
  args:
    chdir: ~/git/ansible-{{ branch }}
  when: git_branch.rc == 1
  tags: ansible

# Use --system-site-packages in order to use selinux package (provided by libselinux-python rpm)
# https://dmsimard.com/2016/01/08/selinux-python-virtualenv-chroot-and-ansible-dont-play-nice/
# https://github.com/ansible/ansible/issues/34340#issuecomment-355214723
- name: Create ansible virtualenv
  shell: . /usr/bin/virtualenvwrapper.sh && mkvirtualenv --python /usr/bin/python3 --system-site-packages ansible-{{ branch }}
  args:
    executable: /bin/bash
  environment:
    VIRTUALENVWRAPPER_PYTHON: /usr/bin/python3
  tags: ansible

- name: Add ansible requirements to venv
  shell: . /usr/bin/virtualenvwrapper.sh && workon ansible-{{ branch }} && pip install -U -r requirements.txt
  args:
    executable: /bin/bash
    chdir: ~/git/ansible-{{ branch }}
  environment:
    VIRTUALENVWRAPPER_PYTHON: /usr/bin/python3
  tags: ansible

- name: Create ansible alias
  lineinfile:
    path: ~/.bashrc
    line: alias a='workon ansible-devel; source ~/git/ansible-devel/hacking/env-setup > /dev/null 2>&1; ansible --version | head -1'
  tags: ansible
  when: branch == "devel"

- name: Disable host key checking when running Ansible
  lineinfile:
    path: ~/.bashrc
    line: export ANSIBLE_HOST_KEY_CHECKING=False
  tags: ansible
  when: branch == "devel"

# https://docs.ansible.com/ansible/latest/reference_appendices/config.html#ansible-configuration-settings-locations
- name: Copy ansible.cfg to home directory
  copy:
    src: ansible/ansible.cfg
    dest: ~/.ansible.cfg
    mode: 0755
  tags: ansible
