- name: Add ansible project, branch {{ branch }}
  git:
    dest: /home/vagrant/git/ansible-{{ branch }}
    repo: git@github.com:ansible/ansible.git
    accept_hostkey: yes
  tags: ansible

- name: Get current branch
  shell: git branch | grep '{{ branch }}'
  args:
    chdir: /home/vagrant/git/ansible-{{ branch }}
  register: git_branch
  failed_when: git_branch.rc > 1
  tags: ansible

- name: Check out branch
  command: git checkout {{ branch }}
  args:
    chdir: /home/vagrant/git/ansible-{{ branch }}
  when: git_branch.rc == 1
  tags: ansible

- name: Create ansible virtualenv
  shell: . /usr/bin/virtualenvwrapper.sh && mkvirtualenv --python /usr/bin/python2 ansible-{{ branch }}
  args:
    executable: /bin/bash
  environment:
    VIRTUALENVWRAPPER_PYTHON: /usr/bin/python3
  tags: ansible

- name: Add ansible requirements to venv
  shell: . /usr/bin/virtualenvwrapper.sh && workon ansible-{{ branch }} && pip install -r requirements.txt
  args:
    executable: /bin/bash
    chdir: /home/vagrant/git/ansible-{{ branch }}
  environment:
    VIRTUALENVWRAPPER_PYTHON: /usr/bin/python3
  tags: ansible

- name: Create ansible alias
  lineinfile:
    path: /home/vagrant/.bashrc
    line: alias a='workon ansible-devel; source /home/vagrant/git/ansible-devel/hacking/env-setup > /dev/null 2>&1; ansible --version | head -1'
  tags: ansible
  when: branch == "devel"

- name: Disable host key checking when running Ansible
  lineinfile:
    path: /home/vagrant/.bashrc
    line: export ANSIBLE_HOST_KEY_CHECKING=False
  tags: ansible
  when: branch == "devel"
