- name: Determine if repo has already been created
  stat:
    path: ~/git/awx
  register: repo_dir
  tags: awx

- block:
  - name: Add awx project
    git:
      dest: ~/git/awx
      repo: git@github.com:jladdjr/awx.git
      accept_hostkey: yes
    tags: awx

  - name: Determine which remotes exist
    command: git remote -v
    args:
      chdir: ~/git/awx
    register: git_remote
    tags: awx

  - name: Add remote repo (ansible)
    command: git remote add ansible git@github.com:ansible/awx.git
    args:
      chdir: ~/git/awx
    when: git_remote.stdout.find('ansible') == -1
    tags: awx

  - name: Fetch ansible repo
    command: git fetch ansible
    args:
      chdir: ~/git/awx
    tags: awx
  when: not repo_dir.stat.exists

- name: Clear existing awx virtualenv
  shell: . /usr/local/bin/virtualenvwrapper.sh && rmvirtualenv awx
  args:
    executable: /bin/bash
  environment:
    VIRTUALENVWRAPPER_PYTHON: /usr/bin/python3.8
  register: venv_list
  tags: awx
  when: recreate_venvs|default(false)

- name: Determine if virtualenv exists
  shell: . /usr/local/bin/virtualenvwrapper.sh && lsvirtualenv -b
  args:
    executable: /bin/bash
  environment:
    VIRTUALENVWRAPPER_PYTHON: /usr/bin/python3.8
  register: venv_list
  tags: awx

- block:
  - name: Create awx virtualenv
    shell: . /usr/local/bin/virtualenvwrapper.sh && mkvirtualenv --python /usr/bin/python3.8 awx
    args:
      executable: /bin/bash
    environment:
      VIRTUALENVWRAPPER_PYTHON: /usr/bin/python3.8
    tags: awx

  - name: Install venv requirements
    shell: . /usr/local/bin/virtualenvwrapper.sh && workon awx && pip install -U -r requirements/requirements_dev.txt
    args:
      executable: /bin/bash
      chdir: ~/git/awx
    environment:
      VIRTUALENVWRAPPER_PYTHON: /usr/bin/python3.8
    tags: awx

  - name: Install awxkit
    shell: . /usr/local/bin/virtualenvwrapper.sh && workon awx && pip install -U -e awxkit
    args:
      executable: /bin/bash
      chdir: ~/git/awx
    environment:
      VIRTUALENVWRAPPER_PYTHON: /usr/bin/python3.8
    tags: awx
  when: "'awx' not in venv_list.stdout"

- name: Create awx alias and derez / preload_tower / wipe_instance functions
  blockinfile:
    path: ~/.bashrc
    block: |
      alias a="workon awx; cd ~/git/awx; python --version | head -1; git br | grep '*'"
      alias ak="workon awx; cd ~/git/awx/awxkit; python --version | head -1; git br | grep '*'"

      # Thoroughly remove awx containers, images and ui build artifacts
      derez () {
          docker ps --all -q | xargs docker stop
          docker ps --all -q | xargs docker rm
          make docker-clean
          make clean
          make docker-clean-volumes
          docker ps --all
          docker images
      }

      rmdb () {
          docker stop tools_postgres_1
          docker rm tools_postgres_1
      }

      # Clear UI artifacts, rebuild UI
      rebuild_ui () {
          make clean-ui
          make ui-devel
      }

      preload_tower () {
          # admin user already exists on fresh deployment of dev environment
          #docker exec -ti tools_awx_1 bash -c 'awx-manage createsuperuser --username=admin --email=admin@localhost --no-input'
          docker exec -ti tools_awx_1 bash -c 'awx-manage update_password --username=admin --password=password'
          docker exec -ti tools_awx_1 bash -c 'awx-manage create_preload_data'
      }

      wipe_instance () {
          docker stop tools_awx_1
          docker rm tools_awx_1
          docker stop tools_postgres_1
          docker rm tools_postgres_1
      }

      alias update_settings='cp awx/settings/local_settings.py.docker_compose awx/settings/local_settings.py'
    marker: "# {mark} ANSIBLE MANAGED BLOCK - awx"
  tags: awx

- name: Add .ignore file (for ag)
  copy:
    src: files/ag/dot_ignore
    dest: ~/git/awx/.ignore
  tags: awx
