- name: Add awx project
  git:
    dest: ~/git/awx
    repo: git@github.com:jladdjr/awx.git
    accept_hostkey: yes

- name: Determine which remotes exist
  command: git remote -v
  args:
    chdir: ~/git/awx
  register: git_remote

- name: Add remote repo (ansible)
  command: git remote add ansible git@github.com:ansible/awx.git
  args:
    chdir: ~/git/awx
  when: git_remote.stdout.find('ansible') == -1

- name: Fetch ansible repo
  command: git fetch ansible
  args:
    chdir: ~/git/awx

- name: Create awx virtualenv
  shell: . /usr/bin/virtualenvwrapper.sh && mkvirtualenv --python /usr/bin/python3 awx
  args:
    executable: /bin/bash
  environment:
    VIRTUALENVWRAPPER_PYTHON: /usr/bin/python3

- name: Create awx aliases
  blockinfile:
    path: ~/.bashrc
    block: |
      alias awx="workon awx; cd ~/git/awx; python --version | head -1; git br | grep '*'"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - awx"

- name: Add .ignore file (for ag)
  copy:
    src: files/ag/dot_ignore
    dest: ~/git/awx/.ignore
