- name: Create git directory
  file:
    state: directory
    path: ~/git
    mode: 0755

# Must tag both include_tasks task as well as tasks in included file:
# https://github.com/ansible/ansible/issues/30882#issuecomment-399483839
- include_tasks: tower-qa.yml
  loop:
    - devel
    - release_3.4.0
    - release_3.3.3
    #- release_3.2.9
    #- release_3.1
  loop_control:
    loop_var: branch
  tags: tower-qa

- include_tasks: towerkit.yml
  tags: towerkit

- include_tasks: ansible.yml
  loop:
    - devel
    - stable-2.7
    - stable-2.6
    - stable-2.5
  loop_control:
    loop_var: branch
  tags: ansible

- include_tasks: pytest-mp.yml
  tags: pytest-mp

- include_tasks: awx.yml
  tags: awx

- include_tasks: tower.yml
  tags: tower

- include_tasks: ansible-runner.yml
  tags: runner

- include_tasks: tower-packaging.yml
  tags: tower-packaging

- include_tasks: ansible-engineering.yml
  tags: ansible-engineering
