- name: Create git directory
  file:
    state: directory
    path: /home/vagrant/git
    mode: 0755
- include_tasks: tower-qa.yml
  loop:
    - master
    - release_3.2
    - release_3.1
  loop_control:
    loop_var: branch
  tags: tower-qa
- include_tasks: towerkit.yml
  tags: towerkit
- include_tasks: pytest-mp.yml
  tags: pytest-mp
- include_tasks: awx.yml
  tags: awx
- include_tasks: tower.yml
  tags: tower
