- name: Create git directory
  file:
    state: directory
    path: ~/git
    mode: 0755

# Must tag both include_tasks task as well as tasks in included file:
# https://github.com/ansible/ansible/issues/30882#issuecomment-399483839
- include_tasks: tower-qa.yml
  loop:
    - devel
    - release_3.7.0
  loop_control:
    loop_var: branch
  tags: tower-qa

- include_tasks: ansible.yml
  loop:
    - devel
    - stable-2.9
  loop_control:
    loop_var: branch
  tags: ansible

- include_tasks: awx.yml
  tags: awx

- include_tasks: tower.yml
  tags: tower

- include_tasks: ansible-runner.yml
  tags: runner

- include_tasks: tower-packaging.yml
  tags: tower-packaging

- include_tasks: ansible-engineering.yml
  tags: ansible-engineering
