- name: Add towerkit project
  git:
    dest: ~/git/towerkit
    repo: git@github.com:jladdjr/towerkit.git
    version: devel
    accept_hostkey: yes
  tags: towerkit

- name: Create towerkit virtualenv
  shell: . /usr/local/bin/virtualenvwrapper.sh && mkvirtualenv --python /usr/bin/python3 towerkit
  args:
    executable: /bin/bash
  environment:
    VIRTUALENVWRAPPER_PYTHON: /usr/bin/python3
  tags: towerkit

- name: Add towerkit requirements to venv
  shell: . /usr/local/bin/virtualenvwrapper.sh && workon towerkit && pip install -r requirements.txt
  args:
    executable: /bin/bash
    chdir: ~/git/towerkit
  environment:
    VIRTUALENVWRAPPER_PYTHON: /usr/bin/python3
  tags: towerkit

- name: Determine which remotes exist
  command: git remote -v
  args:
    chdir: ~/git/towerkit
  register: git_remote
  tags: towerkit

- name: Add remote repo (ansible)
  command: git remote add ansible git@github.com:ansible/towerkit.git
  args:
    chdir: ~/git/towerkit
  when: git_remote.stdout.find('ansible') == -1
  tags: towerkit

- name: Create towerkit aliases
  blockinfile:
    path: ~/.bashrc
    block: |
      export AWXKIT_BASE_URL='http://127.0.0.1:8013'
      alias mach='echo ${AWXKIT_BASE_URL:8}'
      export AWXKIT_SCHEMA_VALIDATION=False
      export AWXKIT_CREDENTIAL_FILE='/home/jim/git/tower-qa-devel/config/credentials.yml'
      export AWXKIT_PROJECT_FILE='/home/jim/.akit/projects.yml'
      export AWXKIT_USER='admin'
      export AWXKIT_USER_PASSWORD='fo0m4nchU'
      alias tk="cd ~/git/towerkit; vw; workon towerkit; python --version | head -1; git br | grep '*'"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - towerkit"
  tags: towerkit

- name: Make .akit config directory
  file:
    dest: ~/.akit
    state: directory
    mode: 0755

- name: Create projects (scm url) file
  copy:
    src: akit/projects.yml
    dest: ~/.akit/projects.yml
    mode: 0755
