- name: Add tower project
  git:
    dest: /home/vagrant/git/tower
    repo: git@github.com:jladdjr/tower.git
    accept_hostkey: yes

- name: Determine which remotes exist
  command: git remote -v
  args:
    chdir: /home/vagrant/git/tower
  register: git_remote

- name: Add remote repo (ansible)
  command: git remote add ansible git@github.com:ansible/tower.git
  args:
    chdir: /home/vagrant/git/tower
  when: git_remote.stdout.find('ansible') == -1

- name: Fetch ansible repo
  command: git fetch ansible
  args:
    chdir: /home/vagrant/git/tower

- name: Create tower virtualenv
  shell: . /usr/bin/virtualenvwrapper.sh && mkvirtualenv --python /usr/bin/python2 tower
  args:
    executable: /bin/bash
  environment:
    VIRTUALENVWRAPPER_PYTHON: /usr/bin/python3

# https://github.com/capless/warrant/issues/96#issuecomment-381503013
- name: Downgrade pip
  shell: . /usr/bin/virtualenvwrapper.sh && workon tower && pip install pip==9.0.3
  args:
    executable: /bin/bash
  environment:
    VIRTUALENVWRAPPER_PYTHON: /usr/bin/python3

- name: Create tower aliases
  blockinfile:
    path: /home/vagrant/.bashrc
    block: |
      alias tower="cd /home/vagrant/git/tower; git br | grep '*'"
      marker: "# {mark} ANSIBLE MANAGED BLOCK - tower"
