- name: Ensure mapped folder exists
  file:
    path: /var/mapped
    state: directory
    mode: 0700

- name: Create neomutt repo
  copy:
    src: flatcap-neomutt-epel-7.repo
    dest: /etc/yum.repos.d
  become: true

- name: Install mutt + dependencies
  yum:
    name: ['neomutt', 'notmuch', 'msmtp', 'offlineimap', 'lynx', 'pandoc']
    state: present
  become: true

- name: Update Lynx settings
  lineinfile:
    path: /etc/lynx.cfg
    line: REFERER_WITH_QUERY:PARTIAL
  become: true

- name: Copy neomuttrc to /etc
  copy:
    src: neomuttrc
    dest: /etc
    mode: 0644
  become: true

- name: Copy mutt / notmuch dotfiles
  copy:
    src: "{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}"
    mode: 0600
  with_items:
    - .neomuttrc.work
    - .neomuttrc.personal
    - .notmuch-config
    - .gpg.rc

- name: Create offlineimaprc / msmtprc dotfiles (requires mutt passwords)
  template:
    src: "{{ item }}"
    dest: "~/{{ item|replace('.j2','') }}"
    mode: 0600
  with_items:
    - .offlineimaprc.j2
    - .msmtprc.j2

- name: Create .mutt folder
  copy:
    src: .mutt
    dest: "{{ lookup('env', 'HOME') }}"
    mode: 0700

- name: Is mapped/.mail folder present?
  command: file /var/mapped/.mail
  register: dotmail

- name: .. if not, create the file
  copy:
    src: mapped/.mail
    dest: /var/mapped
    mode: 0700
  when: dotmail.stdout.find('No such file or directory') != -1

- name: Ensure alias file exists in shared folder
  file:
    path: /var/mapped/alias
    state: touch

- name: Run offlineimap periodically (uncomment job after syncing mail with `offlineimap` for the first time)
  cron:
    name: offlineimap
    minute: "*/5"
    job: "/usr/bin/offlineimap -1 -u quiet"

- name: Create folder for storing mutt attachments
  file:
    path: /var/mapped/mutt
    state: directory
    mode: 0700

- name: Create tmp folder for mutt
  file:
    path: /var/mapped/mutt/tmp
    state: directory
    mode: 0700

- name: Add .bashrc aliases
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK - mutt"
    path: ~/.bashrc
    block: |
      alias nm='pushd .; cd /var/mapped/mutt; neomutt -F ~/.neomuttrc.work; popd'
      alias nm2='pushd .; cd /var/mapped/mutt; neomutt -F ~/.neomuttrc.personal; popd'
