- name: Ensure mapped folder exists
  file:
    path: /home/vagrant/mapped
    state: directory
    mode: 0700

- name: Create neomutt repo
  copy:
    src: flatcap-neomutt-epel-7.repo
    dest: /etc/yum.repos.d
  become: true

- name: Install mutt + dependencies
  yum: name={{ item }} state=present
  with_items:
    - neomutt
    - notmuch
    - msmtp
    - offlineimap
    - lynx
  become: true

- name: Copy neomuttrc to /etc
  copy:
    src: neomuttrc
    dest: /etc
    mode: 0644
  become: true

- name: Copy mutt / notmuch dotfiles
  copy:
    src: "{{ item }}"
    dest: /home/vagrant/
    mode: 0600
  with_items:
    - .neomuttrc.work
    - .neomuttrc.personal
    - .notmuch-config

- name: Create offlineimaprc / msmtprc dotfiles (requires mutt passwords)
  template:
    src: "{{ item }}"
    dest: "/home/vagrant/{{ item|replace('.j2','') }}"
    mode: 0600
  with_items:
    - .offlineimaprc.j2
    - .msmtprc.j2

- name: Create .mutt folder
  copy:
    src: .mutt
    dest: /home/vagrant/
    mode: 0700

- name: Is mapped/.mail folder present?
  command: file /home/vagrant/mapped/.mail
  register: dotmail

- name: .. if not, create the file
  copy:
    src: mapped/.mail
    dest: /home/vagrant/mapped
    mode: 0700
  when: dotmail.stdout.find('No such file or directory') != -1

- name: Ensure alias file exists in shared folder
  file:
    path: /home/vagrant/mapped/alias
    state: touch

- name: Run offlineimap periodically (uncomment job after syncing mail with `offlineimap` for the first time)
  cron:
    name: offlineimap
    minute: "*/5"
    job: "#/usr/bin/offlineimap -1 -u quiet"

- name: Add .bashrc aliases
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK - mutt"
    path: /home/vagrant/.bashrc
    block: |
      alias nm='neomutt -F ~/.neomuttrc.work'
      alias nm2='neomutt -F ~/.neomuttrc.personal'
