- name: install mutt + dependencies
  pacman: name={{ item }} state=present
  with_items:
    - neomutt
    - notmuch
    - msmtp
    - offlineimap
- name: (TODO) Copy over required files
  debug:
    msg: "(TODO) Copy over required files"
- name: (TODO) Add cron job to run offlineimap
  debug:
      msg: "(TODO) Add cron job to run offlineimap: */8 * * * * /usr/bin/offlineimap -u quiet"
- name: Add .bashrc aliases
  blockinfile:
     marker: "# {mark} ANSIBLE MANAGED BLOCK - mutt"
     path: /home/vagrant/.bashrc
     block: |
         alias nm='neomutt'
