---

# As of 9/16/21, minikube requires Docker 18.09 or higher
# # https://minikube.sigs.k8s.io/docs/drivers/docker/

# https://docs.docker.com/engine/install/rhel/#install-using-the-repository
# # I wasn't able to use docker's repositories. When I went to install docker-ce
# # it simply said that all repositories had been tried.

# https://linuxconfig.org/how-to-install-docker-in-rhel-8

# don't think dnf, yum_repository support this
# https://github.com/ansible/ansible/issues/46963
- name: Install docker repo
  shell:
    cmd: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
    warn: false
  become: true

# # sudo dnf install docker-ce
- name: Install docker
  dnf:
    name: docker-ce
    state: latest
  become: true

# This installs:
# - docker-ce 3:20.10.8-3.el8 (using docker-ce-stable)
#       - tells systemctl to create docker.service
#       - creates `docker` group
# And installs the following requirements:
# - containerd.io:  1.4.9-3.1.el8 (docker-ce-stable)
#       - tells systemctl to create containerd.service
# - container-selinux: 2:2.164.1.1 (rhel-8-for-x86_64-appstream-rpms)
#       - sets se policy to 'targeted' for docker, container, gear
# - docker-ce-cli 1:20.10.8-3.el8 (docker-ce-stable)
# - docker-ce-rootless-extras 20.10.8-3.el8 (docker-ce-stable)
# - docker-scan-plugin (rhel-8-baseos-rhui-rpms)
# - fuse-common (rhel-8-appstream-rhui-rpms)
# - fuse-overlayfs 1.6-1 (rhel-8-baseos-rhui-rpms)
#       - modprobe fuse
# - fuse3 3.2.1-12.el8 (rhel-8-baseos-rhui-rpms)
# - fuse3-libs 3.2.1-12.el8 (rhel-8-baseos-rhui-rpms)
# - iptables (rhel-8-baseos-rhui-rpms)
#       - removes alternatives for iptables, ip6tables
#         before doing install
# - libcgroup 0.42-19.e08 (rhel-8-baseos-rhui-rpms)
#       - creates `cgred` group
# - libnetfilter_conntrack (rhel-8-baseos-rhui-rpms)
#       - runs /sbin/ldconfig
# - libnfnetlink (rhel-8-baseos-rhui-rpms)
# - libnftnl (rhel-8-baseos-rhui-rpms)
# - libslirp (rhel-8-appstream-rhui-rpms)
# - slirp4netns (rhel-8-appstream-rhui-rpms)

# Before starting docker for the first time, tell it to
# always let systemd manage cgroups
# https://lwn.net/Articles/676831/
# https://github.com/kubernetes/kubeadm/issues/1394#issuecomment-461443286
# https://docs.docker.com/engine/reference/commandline/dockerd/

- name: Ensure /etc/docker exists
  file:
    path: /etc/docker
    state: directory
    mode: '0755'
  become: true

- name: Ensure docker lets systemd manage cgroups and uses overlay2 fs
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }
  become: true

- name: Enable/Start docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  become: true

# will only take effect once new session is started
# (or 'newgrp docker' is called)
- name: Spare (current) user from having to use sudo with docker run
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
  become: true

- name: get docker info
  shell: docker info
  become: true
  register: docker_info

- name: Check docker's cgroup driver
  fail:
    msg: "Docker not using systemd to manage cgroups"
  when: "'Cgroup Driver: systemd' not in docker_info.stdout"

- name: Check docker's storage driver
  fail:
    msg: "Docker not using overlay2 for storage driver"
  when: "'Storage Driver: overlay2' not in docker_info.stdout"

- name: Check docker's backing filesystem
  debug:
    msg: "Docker not using xfs as backing filesystem"
  when: "'Backing Filesystem: xfs' not in docker_info.stdout"
