- name: Install Python3
  yum:
      name: python36u
      state: present
  become: true
- name: Install Pip3
  yum:
      name: python36u-pip 
      state: present
  become: true
- name: Create link for python3
  file:
      src: /bin/python3.6
      path: /bin/python3
      state: link
      owner: root
      group: root
  become: true  
