- block:
    - name: Update all packages
      yum:
          name: '*'
          state: latest
    - name: Install development tools
      yum:
          name: "@Development tools"
          state: present
    - name: Install other helpful packages
      yum:
          name: "{{ item }}"
          state: present
      with_items:
          - net-tools
          - pass
    # https://stackoverflow.com/questions/22073516/failed-to-install-python-cryptography-package-with-pip-and-setup-py
    - name: Install cryptography deps
      yum:
          name: "{{ item }}"
          state: present
      with_items:
          - gcc
          - libffi-devel
          - python-devel
          - openssl-devel
    - name: Install nodejs
      yum:
          name: nodejs
          state: latest
    - name: Remove..
      yum:
          name: man-pages
          state: absent
    - name: .. and reinstall man pages. (CentOS minimal install omits man pages)
      yum:
          name: man-pages
          state: present
  become: true
