- name: Update all packages
  yum:
      name: '*'
      state: latest
  become: true
- name: Install development tools
  yum:
      name: "@Development tools"
      state: present
  become: true
# https://stackoverflow.com/questions/22073516/failed-to-install-python-cryptography-package-with-pip-and-setup-py
- name: Install cryptography deps
  yum:
      name: "{{ item }}"
      state: present
  with_items:
      - gcc
      - libffi-devel
      - python-devel
      - openssl-devel
  become: true
