- name: Install tmux
  yum:
      name: tmux
      state: latest
  become: true
- name: Install vim
  yum:
      name: vim
      state: latest
  become: true
- name: Replace vi with vim
  file:
      src: /bin/vim
      dest: /bin/vi
      state: link
      force: yes
  become: true
  tags: test
