- name: Ensure ~/mapped/bin folder exists
  file:
    path: ~/mapped/bin
    state: directory
    mode: 0755
    owner: vagrant
    group: vagrant

- name: Copy alert.sh to mapped folder
  copy:
    src: alerts/alert.sh
    dest: ~/mapped/bin
    mode: 0755
    owner: vagrant
    group: vagrant

- name: Ensure /usr/bin/jim/notifications folder exists
  file:
    path: /usr/bin/jim/notifications
    state: directory
    mode: 0755
    owner: root
    group: root
  become: true

- name: Add notifications folder to PATH
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=/usr/bin/jim/notifications:$PATH'
    state: present

- name: Copy notification scripts to /usr/bin/jim/notifications
  copy:
    src: "alerts/{{ item }}"
    dest: /usr/bin/jim/notifications
    mode: 0755
    owner: root
    group: root
  with_items:
    - run_and_notify
    - notify
    - tower_state_check
  become: true

- name: Start tower_state_check after reboot
  cron:
    name: tower_state_check
    special_time: reboot
    job: "/usr/bin/jim/notifications/tower_state_check"
