- name: Ensure /usr/bin/jim/notifications folder exists
  file:
    path: /usr/bin/jim/notifications
    state: directory
    mode: 0755
    owner: root
    group: root
  become: true

- name: Add /usr/bin/jim/notifications folder to PATH
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=/usr/bin/jim/notifications:$PATH'
    state: present

- name: Copy github_notification_check.sh script to /usr/bin/jim/notifications
  copy:
    src: checks/github_notification_check.sh
    dest: /usr/bin/jim/notifications
    mode: 0755
    owner: root
    group: root
  become: true