- name: Ensure /var/mapped/bin folder exists
  file:
    path: /var/mapped/bin
    state: directory
    mode: 0755

- name: Copy open_link to mapped folder
  copy:
    src: open_links/open_link
    dest: /var/mapped/bin
    mode: 0755

- name: Ensure /usr/bin/jim/ folder exists
  file:
    path: /usr/bin/jim
    state: directory
    mode: 0755
  become: true

- name: Add /usr/bin/jim folder to PATH
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=/usr/bin/jim:$PATH'
    state: present

- name: Copy open_link_on_host script to /usr/bin/jim
  copy:
    src: open_links/open_link_on_host
    dest: /usr/bin/jim
    mode: 0755
  become: true
