# Note that wait_for_tower.yml requires notify script
# provided by alerts tasks

- name: Create ansible29 virtualenv
  shell: . /usr/local/bin/virtualenvwrapper.sh && mkvirtualenv ansible29
  args:
    executable: /bin/bash
  environment:
    VIRTUALENVWRAPPER_PYTHON: /usr/bin/python3

- name: Install Ansible and requirements for wait_for_tower in venv
  shell: . /usr/local/bin/virtualenvwrapper.sh && workon ansible29 && pip install -U -I ansible boto3
  args:
    executable: /bin/bash
  environment:
    VIRTUALENVWRAPPER_PYTHON: /usr/bin/python3

- name: Create alias to source ansible
  lineinfile:
    path: ~/.bashrc
    line: alias ans29='workon ansible29; python --version | head -1; ansible --version | head -1'

- name: Ensure /usr/bin/jim/wait_for_tower folder exists
  file:
    path: /usr/bin/jim/wait_for_tower
    state: directory
    mode: 0755
    owner: root
    group: root
  become: true

- name: Add wait_for_tower folder to PATH
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=/usr/bin/jim/wait_for_tower:$PATH'
    state: present

- name: Copy wait_for_tower scripts to /usr/bin/jim/wait_for_tower
  copy:
    src: "wait_for_tower/{{ item }}"
    dest: /usr/bin/jim/wait_for_tower
    mode: 0755
    owner: root
    group: root
  with_items:
    - inventory
    - wait_for_tower
    - wait_for_tower.yml
  become: true

- name: Add .bashrc alias / `CLUSTER_INSTANCE_1` string
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK - wait_for_tower"
    path: ~/.bashrc
    block: |
      alias i='cat ~/tower_instances'
      alias ii="cat ~/tower_instances | tail -n 1 | awk '{print \$3}'"
      export CLUSTER_INSTANCE_1="devel-ansible-devel-cluster-1"
