- name: Install libnotify-bin (provides notify-send cmd used by gimme bash func
  apt:
    name: libnotify-bin
    state: latest
  become: true

- name: Add bash configuration
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK - levelX"
    path: ~/.bashrc
    block: |
      unset AUTOLOAD_VENV_COMPLETE
      autoload_venv () {
          if ! [ -z "$AUTOLOAD_VENV_COMPLETE" ]; then
              return 0
          fi
          export AUTOLOAD_VENV_COMPLETE="true"
          CURR_DIR=$(pwd)
          # exit if not in git dir
          if ! [[ $CURR_DIR == *"/home/jim/git"* ]]; then
              return 0
          fi
          if [ -f .venv_does_not_exist ]; then
              return 0
          fi
          repo=$(echo $CURR_DIR | grep -oP "git/\K[a-z\-]*")
          workon $repo 2>/dev/null
          if ! [[ $? -eq 0 ]]; then
              echo "Couldn't load $repo venv"
              touch .venv_does_not_exist
          fi
      }
      export PROMPT_COMMAND="autoload_venv; $PROMPT_COMMAND"

      alias big_spends="ledger -f ladds.ledger register -S amount Liabilities:Chase --real --head 15; echo ''; ledger -f ladds.ledger register -S amount Assets:NCSECU:Checking --real --head 15; echo ''; ledger -f ladds.ledger register -S amount Assets:OnPoint --real --head 15"
      alias bal='ledger -f ladds.ledger balance'
      alias bal_real='ledger -f ladds.ledger balance --real'
      alias food='ledger -f ladds.ledger register -S date Expenses:Restaurants'

      gimme () {
              total_mins=$1
              notify-send "You will have ${total_mins} mins"
              sleep "$(( ($1 - 2) * 60 ))"

              notify-send "2 minutes left"
              sleep 120

              i3lock -i ~/.config/i3/iceberg.png
      }
