# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/cron_module.html
- name: Perform weekly system updates (12pm on Sundays)
  cron:
    name: Perform weekly system updates
    user: root
    job: apt update && apt upgrade -y
    minute: '0'
    hour: '12'
    weekday: '0'
  become: true
  tags: general_system_config
  when: hostvars[inventory_hostname].ansible_distribution == 'Debian'
