- name: Copy .gitconfig
  copy:
      src: .gitconfig
      dest: /home/vagrant
      mode: 0755
- name: Copy .tmux.conf
  copy:
      src: .tmux.conf
      dest: /home/vagrant
      mode: 0755
- name: Copy .vimrc
  copy:
      src: .vimrc
      dest: /home/vagrant
      mode: 0755
