---

- name: Determine if ~/git/awx exists
  stat:
    path: "{{ ansible_env.HOME }}/git/awx"
  register: stat_awx

- name: Get awx repo
  git:
    repo: https://github.com/ansible/awx.git
    dest: "{{ ansible_env.HOME }}/git/awx"
    version: devel
  when: not stat_awx.stat.exists

- name: Determine if awx_kube_devel image has been created
  shell: docker images --format "{{ '{{.Repository}}' }}"
  register: docker_images

- name: Install nodejs
  dnf:
    name: nodejs
    state: latest
  become: true

- name: Build UI
  shell: make clean-ui && make ui-devel
  args:
    chdir: "{{ ansible_env.HOME }}/git/awx"

- name: Create kubernetes images locally
  shell: export COMPOSE_TAG='{{ MINIKUBE_COMPOSE_TAG }}'; make awx-kube-dev-build
  args:
    chdir: "{{ ansible_env.HOME }}/git/awx"
  when: "'awx_kube_devel' not in docker_images.stdout"

- name: Get awx_kube_devel id
  shell: docker images --format "{{ '{{.ID }}' }}" --filter=reference="quay.io/awx/awx_kube_devel"
  register: docker_images_filter

- name: Set awx_kube_devel id
  set_fact:
    awx_kube_devel_id: "{{ docker_images_filter.stdout }}"

- name: Tag image for upload to dockerhub
  shell: docker tag {{ awx_kube_devel_id }} {{ MINIKUBE_DOCKERHUB_REPO }}/awx_kube_devel:{{ MINIKUBE_COMPOSE_TAG }}

- name: Authenticate with dockerhub
  shell: docker login -u {{ MINIKUBE_DOCKERHUB_REPO }} -p {{ MINIKUBE_DOCKERHUB_TOKEN }}

# do not have perms to push to quay.io
# push to dockerhub instead
- name: Push awx_kube_devel to dockerhub
  shell: docker push {{ MINIKUBE_DOCKERHUB_REPO }}/awx_kube_devel:{{ MINIKUBE_COMPOSE_TAG }}
