---
- name: Install kubernetes pip package
  shell: pip3 install kubernetes==11.0.0
  become: true

- name: Install openshift pip package
  shell: pip3 install openshift
  become: true

- name: Deploy awx
  shell: >
    ansible-playbook ansible/instantiate-awx-deployment.yml
    -e development_mode=yes
    -e image={{ MINIKUBE_DOCKERHUB_REPO }}/awx_kube_devel
    -e image_version={{ MINIKUBE_COMPOSE_TAG }}
    -e image_pull_policy=Always
    -e service_type=nodeport
    -e namespace=default
    -vvv
  args:
    chdir: "{{ ansible_env.HOME }}/git/awx-operator"

- name: How to watch / access awx
  debug:
    msg: |
      To watch the operators progress with deploying awx:
      minikube kubectl -- logs -f deployments/awx-operator

      To see the pods deployed by the operator so far:
      minikube kubectl -- get pods -l "app.kubernetes.io/managed-by=awx-operator"

      To see services deployed by the operator so far:
      minikube kubectl -- get svc -l "app.kubernetes.io/managed-by=awx-operator"

      To access awx:
      $ minikube service awx-service --url

      In general, if a pod is having issues, it can be helpful
      to exec into it and run `journal -f` to see what is happening
      on the system.
