---
- name: Ensure python3 installed
  dnf:
    name: python3
    state: latest
  become: true

- name: Install kubernetes pip package
  shell: pip3 install kubernetes==11.0.0
  become: true

- name: Deploy awx
  shell: >
    ansible-playbook ansible/instantiate-awx-deployment.yml
    -e development_mode=yes
    -e image={{ MINIKUBE_DOCKERHUB_REPO }}/awx_kube_devel
    -e image_version={{ MINIKUBE_COMPOSE_TAG }}
    -e image_pull_policy=Always
    -e service_type=nodeport
    -e namespace=default
  args:
    chdir: "{{ ansible_env.HOME }}/git/awx-operator"
