---

- name: Determine if ~/git/awx-operator exists
  stat:
    path: "{{ ansible_env.HOME }}/git/awx-operator"
  register: stat_awx_operator

- name: Get awx-operator repo (HEAD of devel)
  git:
    repo: https://github.com/ansible/awx-operator.git
    dest: "{{ ansible_env.HOME }}/git/awx-operator"
    version: devel
    refspec: devel
  when: not stat_awx_operator.stat.exists

# alternatively, could maybe pull from somewhere
# though I'm not sure how that's being done at the moment (10/12/21)
- name: build operator image, push to jladdjr/awx-operator:devel
  shell: "make docker-build docker-push IMG=jladdjr/awx-operator:devel"
  args:
    chdir: "{{ ansible_env.HOME }}/git/awx-operator"

# note: namespace must be default
# run the following if this has changed:
# $ minikube kubectl config set-context --current --namespace=default
- name: Deploy operator
  shell: "NAMESPACE=default IMG=jladdjr/awx-operator:devel make deploy"
  args:
    chdir: "{{ ansible_env.HOME }}/git/awx-operator"
