- name: Install hledger
  apt:
    name:
      - hledger
      - ledger  # still required for ledger-mode in Emacs
    state: latest
    update_cache: true
  become: true

# TODO: Install binary from github instead of using package manager
#       (in order to get hledger check command that prints line in
#        expected format)
# VOTE: 1
#
# wget https://github.com/simonmichael/hledger/releases/download/1.32.3/hledger-linux-x64.zip
# unzip hledger-linux-x64.zip
# tar  xvf hledger-linux-x64.tar
# sudo cp hledger* /usr/local/bin
# hledger --version

- name: Add ledger wrapper command
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK - level6 - ledger"
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    block: |
      ledger () {
          cd ~/ledger/2024
          git pull
          /usr/bin/emacsclient -c -a emacs journal.ledger
          git add -u
          git commit -m 'Jim update' && git push
          ssh jim@holodeck 'cd ~/ledger; git pull'
      }

- name: Clone ledger repo from Jeeves
  git:
    repo: ssh://jim@jeeves/~/git/ledger.git
    dest: "{{ lookup('env', 'HOME') }}/ledger"
    version: revolution

- name: Install ledger pre-commit hook
  shell: 'make hooks'
  args:
    chdir: "{{ lookup('env', 'HOME') }}/ledger"
    executable: /bin/bash
