- name: Install hledger
  apt:
    name:
      - hledger
      - ledger  # still required for ledger-mode in Emacs
    state: latest
    update_cache: true
  become: true

# TODO: Install binary from github instead of using package manager
#       (in order to get hledger check command that prints line in
#        expected format)
# VOTE: 1
#
# wget https://github.com/simonmichael/hledger/releases/download/1.32.3/hledger-linux-x64.zip
# unzip hledger-linux-x64.zip
# tar  xvf hledger-linux-x64.tar
# sudo cp hledger* /usr/local/bin
# hledger --version

- name: Add ledger helper functions
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK - level6 - ledger"
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    block: |
      spend () {
        cd ~/ledger
        echo "[Entries for $1]"
        hledger -f journal.ledger --pager=N reg desc:$1
        echo ""

        echo "[Monthly spending for $1]"
        hledger -f journal.ledger --pager=N bal -M -T desc:$1
      }

- name: Clone ledger repo from Seven
  git:
    repo: ssh://jim@seven/~/git/ledger.git
    dest: "{{ lookup('env', 'HOME') }}/ledger"
    version: revolution

- name: Install ledger pre-commit hook
  shell: 'make hooks'
  args:
    chdir: "{{ lookup('env', 'HOME') }}/ledger"
    executable: /bin/bash
