# https://major.io/2021/07/18/tray-icons-in-i3/
- name: Enable tapping
  shell: xinput set-prop "PNP0C50:00 04F3:311D Touchpad" "libinput Tapping Enabled" 1

- name: Persist tapping config change
  lineinfile:
    path: ~/.config/i3/config
    line: exec xinput set-prop "PNP0C50:00 04F3:311D Touchpad" "libinput Tapping Enabled" 1

- name: Enable natural scrolling
  shell: xinput set-prop "PNP0C50:00 04F3:311D Touchpad" "libinput Natural Scrolling Enabled" 1

- name: Persist natural scrolling
  lineinfile:
    path: ~/.config/i3/config
    line: exec xinput set-prop "PNP0C50:00 04F3:311D Touchpad" "libinput Natural Scrolling Enabled" 1

- name: Accelerate mouse motion
  shell: xinput set-prop "PNP0C50:00 04F3:311D Touchpad" "libinput Accel Speed" 0.2

- name: Persist accelerated mouse motion
  lineinfile:
    path: ~/.config/i3/config
    line: exec xinput set-prop "PNP0C50:00 04F3:311D Touchpad" "libinput Accel Speed" 0.2
