# Installs python
# .. but only the console version works
# .. and plugins have to be installed manually using pip

# stanographer has a script that may help with getting the Plover GUI working on the pi
# https://github.com/stanographer/plover-pi/blob/master/plover_raspbian.sh
#
# https://github.com/Anodynous/stenogotchi looks like an amazing project
# that could get a steno board to work over bluetooth

# Installing by wheel seems to be the easiest way to get the latest version
# that can be installed on ARM architecture
- name: Download plover wheel
  get_url:
    # stable as of 12/28/2021
    url: https://github.com/openstenoproject/plover/releases/download/v4.0.0.dev10/plover-4.0.0.dev10-py3-none-any.whl
    dest: /tmp
    owner: pi
    group: pi
    mode: 0755
  become: true

# Installs plover binaries to ~/.local/bin
- name: Install plover from wheel
  shell: /usr/bin/pip install ./plover-4.0.0.dev10+120.g4394ef1-py3-none-any.whl
  args:
    chdir: /tmp

- name: Download dictionaries
  git:
    repo: 'git@github.com:jladdjr/steno-reboot.git'
    dest: ~/steno-reboot
    update: no

- name: Ensure ~/.local/share/plover exists
  file:
    state: directory
    path: ~/.local/share/plover
    mode: 0755

# https://plover.readthedocs.io/en/latest/api/oslayer_config.html#plover.oslayer.config.CONFIG_DIR
- name: Install plover.cfg
  copy:
    src: ~/steno-reboot/plover.cfg
    dest: ~/.local/share/plover/plover.cfg

- name: Add pi to dialout group
  shell: usermod -a -G dialout pi
  become: true

# https://gist.github.com/edro15/1c6cd63894836ed982a7d88bef26e4af
- name: Create udev rules to give steno boards stable /dev paths (note: requires restart to take effect)
  copy:
    src: plover/49-custom.rules
    dest: /etc/udev/rules.d/49-custom.rules
    owner: root
    group: root
    mode: 0644
  become: true

# As of 1/9/2022, getting:
# $ plover -s plover_plugins install plover-python-dictionary
#   2022-01-09 00:23:27,078 [MainThread] ERROR: no such script: plover_plugins
# As a workaround, pip install the plugin's PyPI package directly
- name: Install plover_python_dictionary (out-of-band)
  shell: pip install git+https://github.com/benoit-pierre/plover_python_dictionary.git
