- name: Download plover wheel
  get_url:
    # stable as of 12/28/2021
    #url: https://github.com/openstenoproject/plover/releases/download/continuous/plover-4.0.0.dev10+120.g4394ef1-py3-none-any.whl
    url: https://github.com/openstenoproject/plover/releases/download/v4.0.0.dev10/plover-4.0.0.dev10-py3-none-any.whl
    dest: /tmp
    owner: pi
    group: pi
    mode: 0755
  become: true

# Installs plover binaries to ~/.local/bin
- name: Install plover from wheel
  shell: /usr/bin/pip install ./plover-4.0.0.dev10+120.g4394ef1-py3-none-any.whl
  args:
    chdir: /tmp

- name: Download dictionaries
  git:
    repo: 'git@github.com:jladdjr/steno-reboot.git'
    dest: ~/steno-reboot
    update: no

- name: Ensure ~/.local/share/plover exists
  file:
    state: directory
    path: ~/.local/share/plover
    mode: 0755

# https://plover.readthedocs.io/en/latest/api/oslayer_config.html#plover.oslayer.config.CONFIG_DIR
- name: Install plover.cfg
  copy:
    src: ~/steno-reboot/plover.cfg
    dest: ~/.local/share/plover/plover.cfg

- name: Add pi to dialout group
  shell: usermod -a -G dialout pi
  become: true

# Installing plover_plugins_manager fails while installing PyQt5
# https://stackoverflow.com/a/67606704 suggests upgrading pip to >= 21.1.1
- name: Upgrade pip due to PyQt5 bug
  shell: /home/pi/.local/bin/pip install -U -y pip

# https://plover.readthedocs.io/en/4.0.0-dev8/cli_reference.html#plugin-installer
# plover on raspberry pi is complaining that it cannot find plover_plugins
# Do I need to pip install this?
#     https://github.com/benoit-pierre/plover_plugins_manager.git
- name: Add support for python dictionaries
  shell: ~/.local/bin/plover -s plover_plugins install plover-python-dictionary
