# Provisions host for work

- name: Add target instance if passed in from previous workflow job
  hosts: localhost
  tasks:
    - name: Add host to dev group
      add_host:
        name: "minikube_dev_env"
        ansible_user: "{{ dev_env_user }}"
        ansible_ssh_host: "{{ dev_env_host }}"
        groups: dev
  when: workflow_job|default(false)|bool

- hosts: dev
  roles:
    - awx_on_minikube
