---
- name: Install kubernetes pip package
  shell: pip3 install kubernetes==11.0.0
  become: true

- name: Install openshift pip package
  shell: pip3 install openshift
  become: true

- name: Deploy awx
  shell: >
    ansible-playbook ansible/instantiate-awx-deployment.yml
    -e development_mode=yes
    -e image={{ MINIKUBE_DOCKERHUB_REPO }}/awx_kube_devel
    -e image_version={{ MINIKUBE_COMPOSE_TAG }}
    -e image_pull_policy=Always
    -e service_type=nodeport
    -e namespace=default
    -vvv
  args:
    chdir: "{{ ansible_env.HOME }}/git/awx-operator"

- name: How to watch / debug awx deployment
  debug:
    msg: |
      To watch the operators progress with deploying awx:
      minikube kubectl -- logs -f deployments/awx-operator

      To see the pods deployed by the operator so far:
      minikube kubectl -- get pods -l "app.kubernetes.io/managed-by=awx-operator"

      To see services deployed by the operator so far:
      minikube kubectl -- get svc -l "app.kubernetes.io/managed-by=awx-operator"

      In general, if a pod is having issues, it can be helpful
      to exec into it and run `journal -f` to see what is happening
      on the system.

      To view the minikube dashboard, call:
      minikube dashboard

      If minikube is running on a remote machine, you can create a tunnel to
      view the dashboard.

      For example, if minikube dashboard returns:
      http://127.0.0.1:44937/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/

      .. and the remote host is ec2-3-88-212-173.compute-1.amazonaws.com
      .. create the tunnel using:

      ssh ec2-user@ec2-3-88-212-173.compute-1.amazonaws.com -L 44937:localhost:44937

      To view the dashboard locally, you can use the dashboard address that was originally shown
      (since it already references 127.0.0.1 / localhost).

- name: How to access awx after successful deployment
  debug:
    msg: |
      To access awx:
      $ minikube service awx-service --url

      If awx was deployed on a remote machine..

      .. and awx's url was:
      http://192.168.49.2:31942

      .. create the tunnel using:

      ssh ec2-user@ec2-3-88-212-173.compute-1.amazonaws.com -L 31942:192.168.49.2:31942

      On your local machine, you should now be able to access awx by visiting:
      http://localhost:31942

- name: How to get awx admin password
  debug:
    msg: |
      To get the awx admin password, run:
      minikube kubectl -- get secret awx-admin-password -o jsonpath="{.data.password}" | tr -d '"' | base64 --decode
