---

- import_tasks: docker.yml
  tags: docker
  when: install_prereqs|bool

- import_tasks: awx.yml
  tags: awx
  when: deploy_awx|bool

- import_tasks: minikube.yml
  tags: minikube
  when: deploy_awx|bool

- import_tasks: operator.yml
  tags: operator
  when: deploy_awx|bool

- import_tasks: deploy_awx.yml
  tags: deploy_awl
  when: deploy_awx|bool
