- name: Install misc helpful packages
  apt:
    name:
      - vim
      - info
      - locate
      - bc
      - screen
      - htop
      - strace
      - apt-file
      - e2fsprogs
      - strace
    state: latest
  become: true
