- name: Install custom Dvorak / German keyboard layout
  copy:
    src: keyboard/jim_xkb_layout
    dest: /usr/share/X11/xkb/symbols/jim
    mode: 0644
    backup: yes
  tags: keyboard
  become: true

- name: Install xmodmap config
  copy:
    src: keyboard/dot_Xmodmap
    dest: ~/.Xmodmap
    mode: 0644
    backup: yes
  tags: keyboard

# If the gnome tweak tool was used to swap keys,
# these settings will prevent xcape from working
#
# Note that xcape is called using .config/i3/config
# (as is xmodmap)
#
# ~/.local/share/xorg/Xorg.0.log shows XKBOPTIONS
# that take effect as a result of gnome tweaks /
# /etc/default/keyboard
- name: Ensure no XBOPTIONS set in /etc/default/keyboard
  lineinfile:
    path: /etc/default/keyboard
    regexp: '^XKBOPTIONS='
    line: XKBOPTIONS=""
  become: true

# While XKBOPTIONS should be empty, the
# default keyboard should be set
- name: Ensure keyboard set to 'us'
  lineinfile:
    path: /etc/default/keyboard
    regexp: '^XKBLAYOUT='
    line: XKBLAYOUT="jim"
  become: true

# The variant should also be set
# to the custom variant I created
# where alt can be used with vowels
# to add an umlaut and
# alt can be used with S to create
# the Eszett
- name: Ensure keyboard variant set to 'dvorak-alt-intl'
  lineinfile:
    path: /etc/default/keyboard
    regexp: '^XKBVARIANT='
    line: XKBVARIANT="dvorak-alt-intl"
  become: true
