#- name: Ensure non-free repo is enabled
#  shell: add-apt-repository non-free
#  become: true

# https://brave.com/linux/
- name: Install brave prerequisites
  apt:
    name:
      - apt-transport-https
      - curl
    state: latest
  become: true

- name: Install brave keyring
  shell: curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
  args:
    warn: false
  become: true

- name: Create apt repo for brave
  shell: echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list

- name: Refresh apt cache
  shell: apt update
  become: true

- name: Install brave browser
  apt:
    name: brave-browser
    state: latest
  become: true
