- name: Install taskwarrior
  apt:
    name: taskwarrior
    state: latest
  become: true

- name: Install .taskrc
  copy:
    src: taskwarrior/dot_taskrc
    dest: ~/.taskrc
    mode: 0644
    owner: jim
    group: jim
    backup: yes

- name: Create taskwarrior bash config
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK - taskwarrior"
    path: ~/.bashrc
    block: |
      portladd_tasks () {
        export TASKRC=~/.taskrc.portladds
      }
      jim_tasks () {
        unset TASKRC
        unset TASKDATA
      }

      alias t='task sync; clear; task'
