---
- name: Add commits.to
  git:
    dest: ~/git/commits.to
    repo: git@github.com:jladdjr/commits.to.git
    accept_hostkey: true
  tags: commits_to

- name: Create commits virtualenv
  shell: >
    . /usr/local/bin/virtualenvwrapper.sh && mkvirtualenv
    --python /usr/bin/python3.8 --system-site-packages commits
  args:
    executable: /bin/bash
  environment:
    VIRTUALENVWRAPPER_PYTHON: /usr/bin/python3.8
  tags: commits_to

- name: Add commits_to alias
  lineinfile:
    path: ~/.bashrc
    line: >
      alias c=
      "cd ~/git/commits.to; workon commits;
      python --version | head -1; git br | grep '*'"

- name: Ensure binary deps have been installed
  dnf:
    name: "{{ item }}"
    state: present
  with_items: >
    "{{ lookup('file', '~/git/commits.to/requirements/bindeps').splitlines() }}"
  become: true

- name: Tell postgres to trust local connections
  block:
    - lineinfile:
        regexp: 'local.*all.*all'
        line: 'local all all trust'
        path: /var/lib/pgsql/data/pg_hba.conf

    - name: Tell postgres to trust local connections
      lineinfile:
        regexp: 'host.*all.*all.*127\.0\.0\.1/32'
        line: 'host all all 127.0.0.1/32 trust'
        path: /var/lib/pgsql/data/pg_hba.conf

    - name: Tell postgres to trust local connections
      lineinfile:
        regexp: 'host.*all.*all.*::1/128'
        line: 'host all all ::1/128 trust'
        path: /var/lib/pgsql/data/pg_hba.conf
  become: true

- name: Restart postgres so auth settings can take effect
  service:
    name: postgresql
    state: restarted
  become: true
