- name: Add pom project
  git:
    dest: /home/vagrant/git/pom
    repo: git@github.com:jladdjr/pom.git
    accept_hostkey: yes
- name: Create pom virtualenv
  shell: . /usr/bin/virtualenvwrapper.sh && mkvirtualenv --python /usr/bin/python3 pom
  args:
      executable: /bin/bash
  environment:
      VIRTUALENVWRAPPER_PYTHON: /usr/bin/python3
- name: Create aliases for pom
  lineinfile:
      path: /home/vagrant/.bashrc
      line: alias pom="cd /home/vagrant/git/pom; git br | grep '*'"
- name: Install postgres
  yum:
      name: "{{ item }}"
      state: latest
  with_items:
      - postgresql
      - postgresql-server
  become: true
  tags: test
