- name: Install borgbackup
  apt:
    name:
      - borgbackup
    state: latest
    update_cache: true
  become: true

- name: Ensure scripts directory exists in home folder
  file:
    path: "{{ lookup('env', 'HOME') }}/scripts"
    state: directory
    mode: '0755'

- name: Copy Borg backup script
  copy:
    # look up script using the hostname discovered by ansible
    # https://stackoverflow.com/questions/45908067/whats-the-difference-between-inventory-hostname-and-ansible-hostname
    src: "backup_{{ ansible_hostname }}.sh"
    dest: "{{ lookup('env', 'HOME') }}/scripts/backup.sh"
    mode: 0755
    backup: yes

- name: Create cron job for backups
  cron:
    name: "borg backup"
    hour: "4"
    minute: "0"
    job: "/usr/bin/bash {{ lookup('env', 'HOME') }}/scripts/backup.sh > /dev/null"
