---

# Make docker the default driver
# minikube config set driver docker  # <--- this creates ~/.minikube for the first time

# Before starting docker for the first time, tell it to
# always let systemd manage cgroups
# https://lwn.net/Articles/676831/
# https://github.com/kubernetes/kubeadm/issues/1394#issuecomment-461443286
# https://docs.docker.com/engine/reference/commandline/dockerd/

# sudo mkdir /etc/docker
sudo cat > /etc/docker/daemon.json <<EOF
{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2"
}
EOF

# now we can start docker (and automatically start it in general)
systemctl start docker
systemctl enable docker

# calling systemctl enable docker created:
# /usr/lib/systemd/system/docker.service which had:

# [Unit]
# Description=Docker Application Container Engine
# Documentation=https://docs.docker.com
# After=network-online.target firewalld.service containerd.service
# Wants=network-online.target
# Requires=docker.socket containerd.service
# 
# [Service]
# Type=notify
# # the default is not to use systemd for cgroups because the delegate issues still
# # exists and systemd currently does not support the cgroup feature set required
# # for containers run by docker
# ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
# ExecReload=/bin/kill -s HUP $MAINPID
# TimeoutSec=0
# RestartSec=2
# Restart=always
# 
# # Note that StartLimit* options were moved from "Service" to "Unit" in systemd 229.
# # Both the old, and new location are accepted by systemd 229 and up, so using the old location
# # to make them work for either version of systemd.
# StartLimitBurst=3
# 
# # Note that StartLimitInterval was renamed to StartLimitIntervalSec in systemd 230.
# # Both the old, and new name are accepted by systemd 230 and up, so using the old name to make
# # this option work for either version of systemd.
# StartLimitInterval=60s
# 
# # Having non-zero Limit*s causes performance problems due to accounting overhead
# # in the kernel. We recommend using cgroups to do container-local accounting.
# LimitNOFILE=infinity
# LimitNPROC=infinity
# LimitCORE=infinity
# 
# # Comment TasksMax if your systemd version does not support it.
# # Only systemd 226 and above support this option.
# TasksMax=infinity
# 
# # set delegate yes so that systemd does not reset the cgroups of docker containers
# Delegate=yes
# 
# # kill only the docker process, not all processes in the cgroup
# KillMode=process
# OOMScoreAdjust=-500
# 
# [Install]
# WantedBy=multi-user.target

# I don't want to have to use sudo every time I call `docker run` so:
# https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user

sudo usermod -aG docker $USER
(log out, log back in)

# Once docker is up, confirm that
# - systemd is managing cgroups
# - we're using overlay2

# .. looks like both are true!

#$ docker info
#Client:
# Context:    default
# Debug Mode: false
# Plugins:
#  app: Docker App (Docker Inc., v0.9.1-beta3)
#  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
#  scan: Docker Scan (Docker Inc., v0.8.0)
#
#Server:
# Containers: 0
#  Running: 0
#  Paused: 0
#  Stopped: 0
# Images: 0
# Server Version: 20.10.8
# Storage Driver: overlay2   <----------- good
#  Backing Filesystem: xfs   <----------- looks good (this is from an ec2 instance, but I had 
#  Supports d_type: true                  all of my partitions on the NUC installed with xfs, too)
#  Native Overlay Diff: true
#  userxattr: false
# Logging Driver: json-file
# Cgroup Driver: systemd     <------------  good
# Cgroup Version: 1  <------ Interesting
# Plugins:
#  Volume: local
#  Network: bridge host ipvlan macvlan null overlay
#  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
# Swarm: inactive
# Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
# Default Runtime: runc
# Init Binary: docker-init
# containerd version: e25210fe30a0a703442421b0f60afac609f950a3
# runc version: v1.0.1-0-g4144b63
# init version: de40ad0
# Security Options:
#  seccomp
#   Profile: default
# Kernel Version: 4.18.0-305.el8.x86_64
# Operating System: Red Hat Enterprise Linux 8.4 (Ootpa)
# OSType: linux
# Architecture: x86_64
# CPUs: 4
# Total Memory: 15.46GiB
# Name: ip-192-168-2-96.ec2.internal
# ID: PWG2:XX62:2T4K:DWN7:DV4D:PY6G:YUSY:Z7VY:LEV4:FIES:FDIO:6JVT
# Docker Root Dir: /var/lib/docker
# Debug Mode: false
# Registry: https://index.docker.io/v1/
# Labels:
# Experimental: false
# Insecure Registries:  <----- helpful
#  127.0.0.0/8
# Live Restore Enabled: false

# Tell minikube to use systemd for managing cgroups:
# https://minikube.sigs.k8s.io/docs/faq/#docker-driver-how-can-i-set-minikubes-cgroup-manager

# Enable access to minikube from outside local instance?
# https://minikube.sigs.k8s.io/docs/faq/#how-can-i-access-a-minikube-cluster-from-a-remote-network

# awx wants you to call minikube with certain options set:
# https://github.com/ansible/awx/blob/devel/docs/development/minikube.md
# .. so does the operator:
# https://github.com/ansible/awx-operator

# Info about CNIs (Container Network Interface):
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network

# You don't have to have your awx repo fully setup, but
# should make sure the directory exists. I put a dummy file in there
# so I could make sure that the mount was successful.
#
# mkdir ~/git/awx
# echo "some content" > ~/git/awx/__test__

# minikube start --force-systemd=true \
#                --install-addons=true \
#                --addons=ingress \
#                --cni=flannel \
#                --cpus=4 \
#                --memory=8g \
#                --kubernetes-version=stable \
#                --mount \
#                --mount-string="/path/to/awx:/awx_devel"  <--------- update path
#                
# (command was successful!)

# I did get an error about 
#  ❗  Your cgroup does not allow setting memory.
#      ▪ More information: https://docs.docker.com/engine/install/linux-postinstall/#your-kernel-does-not-support-cgroup-swap-limit-capabilities
#
# Potential fix for that here:
# https://docs.docker.com/engine/install/linux-postinstall/#your-kernel-does-not-support-cgroup-swap-limit-capabilities
# or maybe I should disable the swap altogether?

# as minikube came up, ~/.kube was created
# the only file in it was ~/.kube/config, which has:

# apiVersion: v1
# clusters:
# - cluster:
#     certificate-authority: /home/ec2-user/.minikube/ca.crt
#     extensions:
#     - extension:
#         last-update: Thu, 16 Sep 2021 21:24:04 UTC
#         provider: minikube.sigs.k8s.io
#         version: v1.21.0
#       name: cluster_info
#     server: https://192.168.49.2:8443
#   name: minikube
# contexts:
# - context:
#     cluster: minikube
#     extensions:
#     - extension:
#         last-update: Thu, 16 Sep 2021 21:24:04 UTC
#         provider: minikube.sigs.k8s.io
#         version: v1.21.0
#       name: context_info
#     namespace: default
#     user: minikube
#   name: minikube
# current-context: minikube
# kind: Config
# preferences: {}
# users:
# - name: minikube
#   user:
#     client-certificate: /home/ec2-user/.minikube/profiles/minikube/client.crt
#     client-key: /home/ec2-user/.minikube/profiles/minikube/client.key

# observations made after calling 'minikube up'
# - bringing up minikube did not change /etc/docker
# - /etc/group now has cgred (also appears in /etc/gshadow)

# create an alias so that we always use minikube's kubectl
# alias kubectl="minikube kubectl --"
#
#
# Debug tips:
#
# To see what's happening in the minikube container:
#
# - docker exec -it minikube journalctl -f
# - docker exec -it minikube docker ps
# - docker info minikube

# verify that the mount was successful
#
# minikube ssh
# ls /awx_devel  # should show content
