# https://wiki.znc.in/Installation#Debian
- name: Install znc
  apt:
    name: znc
    state: latest
  become: true

# Install firewalld
# open port 50202

# Configure znc with:
# $ znc --makeconf
#
# The resulting conf file is stored at:
# /home/jim/.znc/configs/znc.conf
#
# TODO: store this file in pass as a secret (?)
# and add task to create this file

# To connect client
# - connect to 192.168.1.3
# - port: 50202
# - SSL: yes
# - nick: (ZNC username)
# - server password: (ZNC password)
# - join rooms: (any rooms configured in ZNC for user)

# To connect to webadmin
# * Tunnel to think w/:
#   ssh -L 50202:localhost:50202 jim@think
# * Point local browser to https://localhost:50202
# * Login with znc user creds (see jladd pass in  $(pass show playbooks/bootstrap/znc-server))
#
# From the webadmin you can:
# - create new users
# - for each user, create new servers, add new rooms to follow
#
# To switch from one server to another w/ ZNC:
# - join the ZNC server
# - send '/msg *status JumpNetwork <name of network>
#   where network name might be Think or libera (see networks defined in webadmin)
