- name: Install Emacs
  apt:
    name:
      - emacs
    state: latest
    update_cache: true
  become: true

- name: Install general tools used by Emacs
  apt:
    name:
      - silversearcher-ag
    state: latest
  become: true

# Install requirements for vterm
- name: Install vterm requirements
  apt:
    name:
      - libvterm-dev
      - cmake
    state: latest
  become: true

- name: Clone emacs.d repo
  git:
    repo: git@github.com:jladdjr/emacs.d.git
    dest: "{{ lookup('env', 'HOME') }}/git/emacs.d"
    version: main

- name: Install Emacs configuration
  shell: 'make install'
  args:
    chdir: "{{ lookup('env', 'HOME') }}/git/emacs.d"
    executable: /bin/bash

