---

- name: Install Syncthing package
  apt: name=syncthing
  become: true

- name: Enable and ensure Syncthing is started
  systemd:
    name: syncthing@{{ syncthing_service_user }}
    enabled: yes
    state: started
  become: true

- name: Install firewalld utils
  apt: name=firewalld
  become: true

# TODO: Should this use `--zone=public`?
- name: Open firewall for syncthing service
  shell: 'firewall-cmd --permanent --zone=public --add-service=syncthing && firewall-cmd --reload'
  args:
    executable: /bin/bash
  become: true
