- name: Install imagemagick
  apt:
    name: imagemagick
    state: latest
  become: true

- name: Install screenshot to /usr/bin/local
  copy:
    src: screenshots/screenshot
    dest: /usr/local/bin
    mode: 0755
    owner: jim
    group: jim
  become: true
