# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/ch-configuring_ntp_using_ntpd
- block:
    - name: Install ntpd
      yum:
        name: ntp
        state: present

    - name: Clear ntp server list
      lineinfile:
        path: /etc/ntp.conf
        regexp: '^server .*$'
        state: absent

    - name: Add ntp servers
      blockinfile:
        path: /etc/ntp.conf
        block: |
          server 0.us.pool.ntp.org
          server 1.us.pool.ntp.org
          server 2.us.pool.ntp.org
          server 3.us.pool.ntp.org

    - name: Increase size of clock adjustments
      lineinfile:
        path: /etc/ntp.conf
        line: tinker step 0.5

    - name: Stop ntpd service
      service:
        name: ntpd
        state: stopped

    - name: Perform manual time sync
      command: ntpd -gq

    - name: Start ntpd service
      service:
        name: ntpd
        state: started

    - name: Resync time (forcefully) every 30 minutes
      cron:
        name: Forcefully reset time
        minute: "*/30"
        job: "systemctl stop ntpd && sleep 5 && /usr/sbin/ntpd -gq && sleep 5 && systemctl start ntpd"
  become: true
