- name: Determine if pass installed
  shell: which pass
  args:
    executable: /bin/bash
  ignore_errors: yes
  register: which_pass
- block:
  # TODO: Need to install newer version of tree for `pass find` to work
  - name: Download pass source
    git:
      dest: /tmp/password-store
      repo: https://git.zx2c4.com/password-store
      version: 1.7.1  # latest version as of 5/2018
  # https://git.zx2c4.com/password-store/tree/INSTALL
  - name: Install pass
    shell: make install
    args:
      chdir: /tmp/password-store
      executable: /bin/bash
    become: true
  - name: Remove pass source
    file:
      path: /tmp/password-store
      state: absent
  when: which_pass.rc != 0
