- name: Determine if pass installed
  shell: which pass
  args:
    executable: /bin/bash
  ignore_errors: yes
  register: which_pass
  tags: pass

- block:
  - name: Ensure tree not installed using yum
    yum:
      name: tree
      state: absent
    become: true

  # http://mama.indstate.edu/users/ice/tree/
  - name: Download tree source
    get_url:
      dest: /tmp/tree-1.7.0.tgz
      url: http://mama.indstate.edu/users/ice/tree/src/tree-1.7.0.tgz

  - name: Extract tree source
    unarchive:
      remote_src: yes
      src: /tmp/tree-1.7.0.tgz
      dest: /tmp

  - name: Install tree
    shell: make & make install
    args:
      executable: /bin/bash
      chdir: /tmp/tree-1.7.0
    become: true

  - name: Remove tree source
    file:
      path: '/tmp/{{ item }}'
      state: absent
    with_items:
      - tree-1.7.0.tgz
      - tree-1.7.0

  - name: Download pass source
    git:
      dest: /tmp/password-store
      repo: https://git.zx2c4.com/password-store
      version: 1.7.1  # latest version as of 5/2018

  # https://git.zx2c4.com/password-store/tree/INSTALL
  - name: Install pass
    shell: |
      export WITH_BASHCOMP="yes"
      make install
    args:
      chdir: /tmp/password-store
      executable: /bin/bash
    become: true

  - name: Remove pass source
    file:
      path: /tmp/password-store
      state: absent
  when: which_pass.rc != 0
  tags: pass

- name: Set PASSWORD_STORE_DIR
  lineinfile:
    path: ~/.bashrc
    line: export PASSWORD_STORE_DIR="/var/mapped/.password-store"
  tags: pass

- name: Ensure .gnupg directory is present
  file:
    path: ~/.gnupg
    mode: 0700
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: directory
  tags: pass

- name: Ensure gpg-agent.conf is present
  file:
    path: ~/.gnupg/gpg-agent.conf
    mode: 0644
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: touch
  tags: pass

- name: Set default-cache-ttl for gpg-agent to one hour
  lineinfile:
    path: ~/.gnupg/gpg-agent.conf
    regexp: 'default-cache-ttl'
    line: 'default-cache-ttl 3600'
  tags: pass

- name: Set max-cache-ttl for gpg-agent to one hour
  lineinfile:
    path: ~/.gnupg/gpg-agent.conf
    regexp: 'max-cache-ttl'
    line: 'max-cache-ttl 3600'
  tags: pass

- name: Reload gpg-agent config
  shell: pkill --signal SIGHUP gpg-agent
  args:
    executable: /bin/bash
  become: true
  ignore_errors: yes  # gpg-agent isn't always up and running
  tags: pass
