- name: Determine if pass installed
  shell: which pass
  args:
    executable: /bin/bash
  ignore_errors: yes
  register: which_pass
  tags: pass

- name: Install pass
  dnf:
    name: pass
    state: latest
  become: true
  when: which_pass.rc != 0
  tags: pass

- name: Enable autocompletion for pass
  lineinfile:
    path: ~/.bashrc
    line: source /usr/share/bash-completion/completions/pass
  tags: pass

- name: Set PASSWORD_STORE_DIR
  lineinfile:
    path: ~/.bashrc
    line: export PASSWORD_STORE_DIR="/var/mapped/.password-store"
  tags: pass

- name: Ensure .gnupg directory is present
  file:
    path: ~/.gnupg
    mode: 0700
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: directory
  tags: pass

- name: Ensure gpg-agent.conf is present
  file:
    path: ~/.gnupg/gpg-agent.conf
    mode: 0644
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: touch
  tags: pass

- name: Set default-cache-ttl for gpg-agent to one hour
  lineinfile:
    path: ~/.gnupg/gpg-agent.conf
    regexp: 'default-cache-ttl'
    line: 'default-cache-ttl 3600'
  tags: pass

- name: Set max-cache-ttl for gpg-agent to one hour
  lineinfile:
    path: ~/.gnupg/gpg-agent.conf
    regexp: 'max-cache-ttl'
    line: 'max-cache-ttl 3600'
  tags: pass

- name: Reload gpg-agent config
  shell: pkill --signal SIGHUP gpg-agent
  args:
    executable: /bin/bash
  become: true
  ignore_errors: yes  # gpg-agent isn't always up and running
  tags: pass
