#################################################################################
# For Fedora33 (12/5/20)
#
# -------------------------------------------------------------------------------
#
# Existing system python:
#
# python3.9
#
# from:
#  dnf package: python3
#
# aliases:
#  - /usr/bin/python3
#  - /usr/bin/python3.9
#
# required by:
#  - dnf      <----- which means you can't uninstall the system python
#
# -------------------------------------------------------------------------------
#
# Existing system pip:
#
# pip-3.9
#
# from:
#  dnf package python3-pip
#
# aliases:
# - /usr/bin/pip
# - /usr/bin/pip-3
# - /usr/bin/pip-3.9
# - /usr/bin/pip3
# - /usr/bin/pip3.9
#  -------------------------------------------------------------------------------
#
#  What we install here:
#
#  python3.6
#
#  from:
#   dnf package python3.6
#
#  aliases:
#  - /usr/bin/python3.6
#
#  .. and ..
#
#  pip3.6
#
#  using get-pip.py with python3.6
#
#  aliases:
#  - /usr/local/bin/pip
#  - /usr/local/bin/pip3
#  - /usr/local/bin/pip3.6
#
#################################################################################

- name: Install python3.6
  dnf:
    name:
      - python3.6  # on fedora33 this does not include pip3.6
    state: present
  become: true
  tags: python

- name: Install pip3.6
  block:
    - name: Get get-pip.py
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /tmp
      tags: python

    - name: Install pip for python3.6
      shell: python3.6 get-pip.py
      args:
        chdir: /tmp
      become: true
      tags: python

- name: Update pip3.6
  shell: pip3.6 install -U pip
  become: true
  tags: python

- name: Install virtualenvwrapper
  shell: pip3.6 install -U virtualenvwrapper
  become: true
  tags: python

- name: Source virtualenvwrapper
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK - virtualenvwrapper"
    path: ~/.bash_profile
    block: |
      export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3.6
      #lazy-load virtualenvwrapper
      source /usr/local/bin/virtualenvwrapper.sh
  tags: python
