- name: Install python3 (including header files)
  dnf:
    name:
      - python3        # Includes several aliases for python [1] and
                       # python3-pip [1]
      - python3-devel
    state: present
  become: true

# [1] as of 6/30/20, python aliases include:
# * /usr/bin/python3
# * /usr/bin/python3.6
# * /usr/bin/python3.6m

# [2] as of 6/30/20, python3-pip includes:
# * /usr/bin/pip-3
# * /usr/bin/pip-3.6
# * /usr/bin/pip3
# * /usr/bin/pip3.6

- name: Create link for python
  file:
    src: /bin/python3
    path: /bin/python
    state: link
    owner: root
    group: root
  become: true

- name: Update pip3
  shell: pip3 install -U pip
  become: true

- name: Install virtualenvwrapper
  shell: pip3 install -U virtualenvwrapper
  become: true

- name: Source virtualenvwrapper
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK - virtualenvwrapper"
    path: ~/.bash_profile
    block: |
      export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
      #lazy-load virtualenvwrapper
      source /usr/local/bin/virtualenvwrapper.sh
