- name: Install Python3 (including header files)
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python36u
    - python36u-devel
  become: true

- name: Install Pip3
  yum:
    name: python36u-pip
    state: present
  become: true

- name: Update Pip3
  shell: pip3.6 install -U pip
  become: true

- name: Create link for python3
  file:
    src: /bin/python3.6
    path: /bin/python3
    state: link
    owner: root
    group: root
  become: true

- name: Install virtualenvwrapper
  shell: pip3.6 install -U virtualenvwrapper
  become: true

- name: Source virtualenvwrapper
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK - virtualenvwrapper"
    path: ~/.bash_profile
    block: |
      export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
      # Don't source virtualenvwrapper.sh; slow to load. Load as needed instead
      #source /usr/bin/virtualenvwrapper.sh
