- block:
    - name: Update all packages
      dnf:
        name: '*'
        state: latest

    - name: Install development tools
      dnf:
        name: "@Development tools"
        state: present

    - name: Install net-tools
      dnf:
        name: net-tools
        state: present

    # https://stackoverflow.com/questions/22073516/failed-to-install-python-cryptography-package-with-pip-and-setup-py
    - name: Install cryptography deps
      dnf:
        name:
          - gcc
          - libffi-devel
          - python3-devel
          - openssl-devel
        state: present

    - name: Install packages required by awx venvs
      dnf:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - openldap-devel
          - libcurl-devel  # for pycurl
          - libxslt-devel  # for ovirt-engine-sdk-python
          - libxml2-devel  # for ovirt-engine-sdk-python

    - name: Remove man pages
      dnf:
        name: man-pages
        state: absent

    - name: Reinstall man pages. (CentOS minimal install omits man pages)
      dnf:
        name: man-pages
        state: present

    - name: Install bash completion
      dnf:
        name: bash-completion
        state: present

    - name: Install locate / updatedb
      dnf:
        name: mlocate
        state: present

    - name: Install htop
      dnf:
        name: htop
        state: present
  become: true
