- block:
   # if I got this wrong, and the kernel *is* updated
   # that can break guest additions
   #
   #- name: Update all packages
   #   dnf:
   #     name: '*'
   #     state: latest
   #     exclude:
   #       - kernel*
   #       - virtualbox-guest-additions

    - name: Install development tools
      dnf:
        name: "@Development tools"
        state: present

    - name: Install net-tools
      dnf:
        name: net-tools
        state: present

    # https://unix.stackexchange.com/a/568275
    - name: Install cron
      dnf:
        name:
          - cronie
          - cronie-anacron

    # https://stackoverflow.com/questions/22073516/failed-to-install-python-cryptography-package-with-pip-and-setup-py
    - name: Install cryptography deps
      dnf:
        name:
          - gcc
          - libffi-devel
          - python3-devel
          - python3-libselinux
          - openssl-devel
        state: present

    - name: Install packages required by awx venvs
      dnf:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - openldap-devel
          - libcurl-devel  # for pycurl
          - libxslt-devel  # for ovirt-engine-sdk-python
          - libxml2-devel  # for ovirt-engine-sdk-python

    - name: Install bash completion
      dnf:
        name: bash-completion
        state: present

    - name: Install locate / updatedb
      dnf:
        name: mlocate
        state: present

    - name: Install htop
      dnf:
        name: htop
        state: present
  become: true
  tags: system-packages
