- name: Install sway and friends
  apt:
    name:
      - sway
      - swaylock
      - swayidle
      - i3status
      - bemenu
    state: latest
    update_cache: true
  become: true

- name: Ensure .sway dir present
  file:
    state: directory
    path: ~/.sway
    mode: 0755

# TODO: Copy over wallpaper folders from i3 folder, too
- name: Install sway config
  copy:
    src: sway_config
    dest: ~/.sway/config
    mode: 0755
    backup: yes

# https://i3wm.org/docs/i3status.html
- name: Install i3status config
  copy:
    src: dot_i3status.conf
    dest: ~/.i3status.conf
    mode: 0755
    backup: yes

- name: Configure sway to use i3status
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.sway/config"
    line: "    status_command i3status -c ~/.i3status.conf"
    regexp: "^    status_command.*$"
    state: present
  become: true
