- name: Install sway
  apt:
    name: sway
    state: latest
  become: true

- name: Ensure .config dir present
  file:
    state: directory
    path: ~/.config
    mode: 0700

- name: Ensure .config/sway dir present
  file:
    state: directory
    path: ~/.config/sway
    mode: 0755

- name: Install sway config
  copy:
    src: sway_config
    dest: ~/.config/sway/config
    mode: 0644
    backup: yes
