- name: Install sway
  apt:
    name: sway
    state: latest
  become: true

- name: Ensure .sway dir present
  file:
    state: directory
    path: ~/.sway
    mode: 0755

- name: Install sway config
  copy:
    src: sway_config
    dest: ~/.sway/config
    mode: 0755
    backup: yes
