# TODO: Configure printer to use US Letter instead of A4
#       and do double-sided printing be default
- hosts: all
  tasks:
    - name: Configure remote printer (via ipp protocol)
      # The ipp address should have a name that matches the printer's name on the server
      shell: 'lpadmin -p HLL2300D -E -v ipp://holodeck/printers/HLL2300D -m everywhere'
      args:
        executable: /bin/bash
      become: true

    - name: Set Brother printer as default
      shell: 'lpoptions -d HL-L2300D-on-holodeck'
      args:
        executable: /bin/bash
      become: true

    - name: Test print page
      shell: 'lp /usr/share/cups/data/testprint'
      args:
        executable: /bin/bash

