- hosts: all
  tasks:
    - name: Enable non-free repository
      lineinfile:
        path: /etc/apt/sources.list
        line: "deb http://deb.debian.org/debian/ bookworm main non-free"
        regexp: "^deb http://deb.debian.org/debian/ bookworm main$"
        state: present
      become: true

    - name: Update apt cache
      shell: "apt update"
      become: true

    # https://www.emacswiki.org/emacs/EmacsForDebian
    # https://emacs.stackexchange.com/questions/7238/info-file-emacs-does-not-exist
    - name: Install Emacs documentation (to support "C-h i")
      apt:
        name: emacs-common-non-dfsg
      update_cache: true
      become: true
