- name: Install latest tmux
  apt:
    name: tmux
    state: latest
    update_cache: true
  become: true

- name: Copy .tmux.conf
  copy:
    src: tmux.conf
    dest: ~/.tmux.conf
    mode: 0755

- name: Create alias for tmux attach
  lineinfile:
    path: ~/.bashrc
    line: "alias ta='tmux attach'"

- name: Create git plugin directory
  file:
    state: directory
    path: ~/.tmux/plugins
    mode: 0755

- name: Install tmux-resurrect
  git:
    dest: ~/.tmux/plugins
    repo: http://github.com/tmux-plugins/tmux-resurrect.git
    version: v4.0.0
    accept_hostkey: yes

- name: Source resurrect.tmux
  lineinfile:
    path: ~/.tmux.conf
    line: run-shell ~/.tmux/plugins/resurrect.tmux
