- name: Ensure tmp directory exists in home folder
  file:
    path: "{{ lookup('env', 'HOME') }}/tmp"
    state: directory
    mode: '0755'

- name: Copy Signal install script to ~/tmp
  copy:
    src: install_signal.sh
    dest: "{{ lookup('env', 'HOME') }}/tmp"
    mode: 0755
    backup: yes

- name: Run Signal install script
  shell: './install_signal.sh'
  args:
    chdir: "{{ lookup('env', 'HOME') }}/tmp"
    executable: /bin/bash
  become: true
