- name: Install redshift
  apt:
    name: redshift
    state: latest
  become: true

# redshift will be started via i3 config
- name: Remove redshift autostart
  file:
    state: absent
    path: ~/.config/autostart/redshift-gtk.desktop
