---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-devel
spec:
  service_type: nodeport
  hostname: awx-demo.example.com
  image: jladdjr/awx_kube_devel
  image_version: "20210916"
  image_pull_policy: Always
