- name: Install Docker
  apt:
    name:
      - docker
      - docker-compose
    state: latest
  become: true

# TODO: Is this still required?
# # May want to use user module instead: https://docs.ansible.com/ansible/latest/modules/user_module.html
# - name: Get current user
#   shell: whoami
#   register: shell
#
# - name: Add {{ shell.stdout }} to docker group (so docker can be run w/out sudo)
#   shell: usermod -a -G docker {{ shell.stdout }}
#   become: true
