# http://www.offlineimap.org/documentation.html
# https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap.conf
- block:
    - name: Install offlineimap3
      apt:
        name: offlineimap3
        state: latest
      become: true
      tags: mail

    - name: Create .offlineimaprc
      template:
        src: offlineimaprc.j2
        dest: ~/.offlineimaprc
        mode: 0700
      tags: mail
  when: hostvars[inventory_hostname].ansible_hostname == 'revolution'
