# TODO: rename this to mail.yml?

# http://www.offlineimap.org/documentation.html
# https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap.conf
- block:
    - name: Install offlineimap3
      apt:
        name: offlineimap3
        state: latest
      become: true
      tags: mail

    - name: Create .offlineimaprc
      template:
        src: offlineimaprc.j2
        dest: ~/.offlineimaprc
        mode: 0700
      tags: mail

    # TODO: Run offlineimap as service
    # https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap.conf

    - name: Install mu4e
      apt:
        name: mu4e
        state: latest
      become: true
      tags: mail

    # TODO: Only run mu init, mu index if mu was installed for first time
    # TODO: Change email address to jim.ladd@mailbox.org
    - name: Initialize mu
      shell: mu init --maildir=/home/jim/mail --my-address=skwreupl@mailbox.org

    - name: Run mu index for first time
      shell: mu index

    - name: Run offlineimap every 30 minutes
      cron:
        name: run offlineimap periodically
        job: "/usr/bin/offlineimap -u quiet"
        minute: "*/30"
  when: hostvars[inventory_hostname].ansible_hostname == 'revolution'
