---

# before running minikube for the first time, disable selinux
- name: Disable selinux (permanent)
  lineinfile:
    path: /etc/sysconfig/selinux
    regexp: '^SELINUX='
    line: SELINUX=disabled
  become: true

- name: Disable selinux (for current session)
  shell: setenforce 0
  become: true

# Per this comment (https://github.com/ansible/awx-operator/issues/548#issuecomment-920972288)
# it looks like Minikube v1.21.0 may be my best best (even though v1.23.0 is out)
# - installs /usr/bin/minikube
- name: Install Minikube v1.21.0
  dnf:
    name: 'https://github.com/kubernetes/minikube/releases/download/v1.21.0/minikube-1.21.0-0.x86_64.rpm'
    state: present
    disable_gpg_check: true
  become: true

# this creates ~/.minikube for the first time
- name: make docker the default driver for minikube
  shell: minikube config set driver docker

# awx repo doesn't have to be populated, but does need to exist
# before starting minikube and asking it to mount the folder
- name: Ensure ~/git/awx exists
  file:
    path: "{{ ansible_env.HOME }}/git/awx"
    state: directory
    mode: '0755'

- name: Ensure /usr/local/bin exists
  file:
    path: "/usr/local/bin"
    state: directory
    mode: '0755'
  become: true

# Tell minikube to use systemd for managing cgroups:
# https://minikube.sigs.k8s.io/docs/faq/#docker-driver-how-can-i-set-minikubes-cgroup-manager

# Enable access to minikube from outside local instance?
# https://minikube.sigs.k8s.io/docs/faq/#how-can-i-access-a-minikube-cluster-from-a-remote-network

# awx wants you to call minikube with certain options set:
# https://github.com/ansible/awx/blob/devel/docs/development/minikube.md
# .. so does the operator:
# https://github.com/ansible/awx-operator

# Info about CNIs (Container Network Interface):
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network

# TODO: Omit '--listen-address=0.0.0.0' by default
- name: Create script to start minikube
  copy:
    dest: /usr/local/bin/start_minikube
    content: |
      minikube start --force-systemd=true \
                     --install-addons=true \
                     --addons=ingress \
                     --cni=flannel \
                     --cpus=4 \
                     --memory=8g \
                     --kubernetes-version=stable \
                     --mount \
                     --mount-string="{{ ansible_env.HOME }}/git/awx:/awx_devel" \
                     --listen-address=0.0.0.0
    mode: '0755'
  become: true

- name: Start minikube
  shell:
    cmd: /usr/local/bin/start_minikube
