---

# before running minikube for the first time, disable selinux
- name: Disable selinux (permanent)
  lineinfile:
    path: /etc/sysconfig/selinux
    regexp: '^SELINUX='
    line: SELINUX=disabled
  become: true

- name: Disable selinux (for current session)
  shell: setenforce 0
  become: true

# Per this comment (https://github.com/ansible/awx-operator/issues/548#issuecomment-920972288)
# it looks like Minikube v1.21.0 may be my best best (even though v1.23.0 is out)
# - installs /usr/bin/minikube
- name: Install Minikube v1.21.0
  dnf:
    name: 'https://github.com/kubernetes/minikube/releases/download/v1.21.0/minikube-1.21.0-0.x86_64.rpm'
    state: present
    disable_gpg_check: true
  become: true

# this creates ~/.minikube for the first time
- name: make docker the default driver for minikube
  shell: minikube config set driver docker

# Before starting docker for the first time, tell it to
# always let systemd manage cgroups
# https://lwn.net/Articles/676831/
# https://github.com/kubernetes/kubeadm/issues/1394#issuecomment-461443286
# https://docs.docker.com/engine/reference/commandline/dockerd/

- name: Ensure /etc/docker existst
  file:
    path: /etc/docker
    state: directory
    mode: '0755'
  become: true

- name: Ensure docker lets systemd manage cgroups and uses overlay2 fs
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }

- name: Enable/Start docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Spare (current) user from having to use sudo with docker run
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
  become: true
