---

# Create an image pull secret if you want to deploy a custom operator image
# that jenkins built and pushed to GCR
#
# https://ryaneschinger.com/blog/using-google-container-registry-gcr-with-minikube/
#
# 1. Go to IAM & Admin -> Service Accounts
#    https://console.cloud.google.com/iam-admin/serviceaccounts?project=ansible-tower-engineering
# 2. Click on "+ CREATE SERVICE ACCOUNT"
# 3. Select Container Registry Service Account when searching for role
# 4. After role is created, open service account, click on KEYS tab, and click on ADD KEY.
# 5. Choose to create a JSON key
# 6. Save key in ~/tmp/gcr_key.json
# 7. Create image pull secret in minikube:
#    kubectl --namespace=default create secret docker-registry gcr-json-key --docker-server=https://gcr.io --docker-username=_json_key --docker-password="$(cat ~/tmp/gcr_key.json)" --docker-email=jladd@redhat.com
#    - note that --docker-username *must* be _json_key
# 8. Save awx-operator CRD at https://github.com/ansible/awx-operator/blob/devel/deploy/awx-operator.yaml
#    (version I used: https://github.com/ansible/awx-operator/blob/c235c6d7e87f9027714474988e9016ee26f277ac/deploy/awx-operator.yaml)
# 9. Set spec.template.spec.containers.image (toward bottom) to something like "gcr.io/ansible-tower-engineering/awx-operator-jladd:latest"
#    and set OPERATOR_VERSION to something reflecting your image's purpose.
# 10. Deploy the operator with:
#     kubectl apply -f awx-operator.yaml
# 11. This will initially fail because it can't pull the image.
# 12. Patch the operator so that it can use the secret created earlier.
#     kubectl --namespace=default patch serviceaccount awx-operator -p '{"imagePullSecrets": [{"name": "gcr-json-key"}]}'
# 13. The pod may immediately begin pulling the image. If it doesn't, use `minikube dashboard` to open the dashboard in the browser, go to Deployments. Click on the three dots and select scale. Scale the deployment down to 0. Wait until all pods are deleted (a matter of secords), then scale it back to 1. The pod should deploy successfully.


