- name: Install fzf
  apt:
    name:
      - fzf
    state: latest
  become: true

- name: Source bash completion for fzf
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    line: "source /usr/share/bash-completion/completions/fzf"

- name: Source bindings for fzf
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    line: "source /usr/share/doc/fzf/examples/key-bindings.bash"
