- name: Ensure mapped folder exists
  file:
    path: /var/mapped
    state: directory
    mode: 0700

- name: Create neomutt repo
  copy:
    src: neomutt/flatcap-neomutt-epel-7.repo
    dest: /etc/yum.repos.d
  become: true

- name: Install neomutt + dependencies
  yum:
    name: ['neomutt', 'notmuch', 'msmtp', 'offlineimap', 'lynx', 'pandoc']
    state: present
  become: true

- name: Update Lynx settings
  lineinfile:
    path: /etc/lynx.cfg
    line: REFERER_WITH_QUERY:PARTIAL
  become: true

- name: Copy neomuttrc to /etc
  copy:
    src: neomutt/neomuttrc
    dest: /etc
    mode: 0644
  become: true

- name: Copy neomutt / notmuch dotfiles
  copy:
    src: neomutt/"{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/.{{ item }}"
    mode: 0600
  with_items:
    - neomuttrc.work
    - neomuttrc.personal
    - notmuch-config
    - gpg.rc

- name: Create offlineimaprc / msmtprc dotfiles (requires neomutt passwords)
  template:
    src: neomutt/"{{ item }}"
    dest: "~/.{{ item|replace('.j2','') }}"
    mode: 0600
  with_items:
    - offlineimaprc.j2
    - msmtprc.j2

- name: Create .mutt folder
  copy:
    src: neomutt/mutt
    dest: "{{ lookup('env', 'HOME') }}/.mutt"
    mode: 0700

- name: Is mapped/.mail folder present?
  command: file /var/mapped/.mail
  register: dotmail

- name: .. if not, create the file
  copy:
    src: neomutt/mapped/mail
    dest: /var/mapped/.mail
    mode: 0700
  when: dotmail.stdout.find('No such file or directory') != -1

- name: Ensure alias file exists in shared folder
  file:
    path: /var/mapped/alias
    state: touch

- name: Run offlineimap periodically (uncomment job after syncing mail with `offlineimap` for the first time)
  cron:
    name: offlineimap
    minute: "*/5"
    job: "bash -c '/usr/bin/imapfilter -l /var/mapped/imapfilter.log -t /etc/ssl/certs/ca-bundle.crt && /usr/bin/offlineimap -1 -u quiet'"

- name: Create folder for storing mutt attachments
  file:
    path: /var/mapped/mutt
    state: directory
    mode: 0700

- name: Create tmp folder for mutt
  file:
    path: /var/mapped/mutt/tmp
    state: directory
    mode: 0700

- name: Add .bashrc aliases
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK - neomutt"
    path: ~/.bashrc
    block: |
      alias nm='pushd .; cd /var/mapped/mutt; neomutt -F ~/.neomuttrc.work; popd'
      alias nm2='pushd .; cd /var/mapped/mutt; neomutt -F ~/.neomuttrc.personal; popd'

- name: Install / configure imapfilter
  import_tasks: imapfilter.yml
