- hosts: all
  tasks:
    - name: Install Gimp
      apt:
        name: gimp
        state: present
      become: true

- hosts: all
  roles:
    - { role: texinfo, tags: texinfo }
    - { role: ledger, tags: ledger }
    - { role: latex, tags: latex }
