- hosts: all
  roles:
    - { role: gimp, tags: gimp }
    - { role: latex, tags: latex }
    - { role: ledger, tags: ledger }
    - { role: texinfo, tags: texinfo }

- hosts: all
  tasks:
    - name: Install krita
      apt:
        name:
          - krita
        state: latest
      become: true
