- hosts: all
  roles:
    - { role: gimp, tags: gimp }
    - { role: latex, tags: latex }
    - { role: ledger, tags: ledger }
    - { role: texinfo, tags: texinfo }
    - { role: qwertify, tags: qwertify }
    # TODO: Install KOReader
    # https://github.com/koreader/koreader/releases

- hosts: all
  tasks:
    - name: Install krita, screenkey, slurp, and wf-recorder
      apt:
        name:
          - krita
          - inkscape
          - screenkey    # run with `screenkey --mods-mode emacs --persist`
          - gocr         # for Optical Character Recognition (OCR)
          - tesseract    # easy-to-use OCR tool
          - units
          - rolldice
        state: latest
        update_cache: true
      become: true

- hosts: all
  tasks:
    - name: Install Dragon Player
      apt:
        name:
          - dragonplayer
        state: latest
      become: true
