[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
capslock = overload(control, esc)

# Remaps the escape key to capslock
# (disabled so that escape is available on polyglot)
# esc = capslock
