# https://synocommunity.com/#easy-install
# https://docs.borgbase.com/setup/synology/
# https://borgbackup.readthedocs.io/en/stable/

# manual steps
# https://docs.borgbase.com/setup/synology/
#
# Create Shared Folder
# - name: BorgBackup
#   - created on only volume currently defined (which uses Btrfs)
# - disable emptying Recycle Bin
# - enable both hide options
#   - hide from "My Network Places"
#   - hide from users without permission to folder
#
# - did not enable self-healing
#   (TODO: would this be helpful? does this take advantage of RAID?)
# - did not enable compression (borg should handle this)
# - set quota to 500 GB (TODO: right size this)
#
# - did *not* share this with the admin account
#   (TODO: is this required by the borg server?)
#
# Add borg user in Synology
# - add to Administrators group, otherwise ssh will be blocked
# - give access to the BorgBackup folder
#
#   borg password can be seen with:
#   pass show -c home/synology/borg_dsm
#
# Create keypair for borg user.
# - In /var/services/homes/borg, create .ssh folder
#   - I created this key with:
#     ssh-keygen -a 20 -f id_rsa -C "borg@jeeves"
#
# - Add keys to jim/keys/borg in pass
#
# - Create authorized_keys (mode 600) (set owner / group to borg)
#   and place public key in file
#
# - Weird bug! Have to make sure to change perms
#   on user's home directory in synology
#   otherwise ssh using public key won't work!
#
#   ssh jim@jeeves
#   sudo su -
#   chmod 755 /var/services/homes/borg
#
#
# Borg client unable to find borg script unless you:
# - ssh jim@jeeves
#   sudo su -
#   (enter jim's dsm password)
#   cd /usr/bin (since this is on the default path)
#   ln -s /usr/local/bin/borg borg
# - This will put borg on the default path used
# - Could alternatively update borg's path to include /usr/local/bin
#
# Initialize a new borg repo with:
#   borg init --encryption=repokey /var/services/homes/borg/repo
- name: Server setup
  debug:
    msg: 'see manual steps listed in borg_server.yml'

# install rclone on jeeves
# https://rclone.org/install/#linux-installation-from-precompiled-binary
# note: use `7z x <path/to/file.zip` instead of unzip

# configure rclone / wasabi
#
# (on Jeeves)
# /var/services/homes/jim/.config/rclone/rclone.conf
#
# [wasabi]
# type = s3
# provider = Wasabi
# access_key_id = <access key, see pass info strode for wasabi)
# secret_access_key = <ditto ^>
# region = us-west-1
# endpoint = s3.us-west-1.wasabisys.com
# location_constraint =
# acl = private
#
# I *think* the location_contstraint is right; it's supposed to be
# blank based on info provided here:
# https://rclone.org/s3/#wasabi

# rclone script example:
# https://opensource.com/article/17/10/backing-your-machines-borg
