# https://docs.inspircd.org/3/installation/debian/
- block:
  - name: Determine if inspircd already installed
    shell: which inspircd
    register: which_inspircd

  - name: Stop inspircd (if already installed)
    service:
      name: inspircd
      state: stopped
    when: which_inspircd.rc == 0

  - name: Install inspircd
    apt:
      name: inspircd
      state: latest
      update_cache: true

  - name: Ensure inspircd config directory exists
    file:
      state: directory
      path: /etc/inspircd
      owner: irc
      group: irc
      mode: 0770

  - name: Copy over config files
    copy:
      src: "{{ item }}"
      dest: /etc/inspircd
      owner: irc
      group: irc
      mode: 0644
    with_items:
      - inspircd.motd
      - inspircd.rules
   
  - name: Copy over templated config files
    template:
      src: inspircd.conf.j2
      dest: /etc/inspircd/inspircd.conf
      owner: irc
      group: irc
      mode: 0644

  # While firewalld is mostly used on RHEL instances,
  # Debian can use it, too
  # https://computingforgeeks.com/how-to-install-and-configure-firewalld-on-debian/
  - name: Install firewalld
    apt:
      name: firewalld
      state: latest

  # To confirm that a firewall rule has taken effect, run:
  # $ sudo firewall-cmd --list-all
  #
  # To verify that a service is listening on a given port, run:
  # $ lsof -i | grep -i listen
  #
  # To verify you can connect to the taskd server from a remote host, run:
  # telnet think 53589

  # TODO: Do I need the irc service, or can I just use ircs?
  - name: Add irc service to firewall
    shell: firewall-cmd --permanent --add-service=irc --zone=public

  - name: Add ircs service to firewall
    shell: firewall-cmd --permanent --add-service=irc --zone=public

  - name: Reload firewalld rules
    shell: firewall-cmd --reload

  - name: Enable inspircd
    service:
      name: inspircd
      enabled: yes

  - name: Start inspircd
    service:
      name: inspircd
      state: started
  become: true
