- name: Install irssi
  apt:
    name: irssi
    state: latest
  become: true

- name: Ensure irssi config directory exists
  file:
    state: directory
    path: ~/.irssi
    mode: 0700

- name: Copy over irssi config
  template:
    src: irssi/config.j2
    dest: ~/.irssi/config
    mode: 0640

- name: Copy over irssi themes
  copy:
    src: "irssi/{{ item }}"
    dest: ~/.irssi
    mode: 0640
  with_items:
    - default.theme
    - old-default.theme
