- name: Install latex
  apt:
    name: texlive
    state: latest
  become: true

- name: Install latex info files
  apt:
    name:
      - info
      - texlive-lang-english
    state: latest
  become: true

- name: Install helpful supplemental latex libraries
  apt:
    name:
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-latex-recommended
    state: latest
  become: true

