- name: Install taskwarrior
  apt:
    name: taskwarrior
    state: latest
  become: true

- name: Install .taskrc
  copy:
    src: taskwarrior/dot_taskrc
    dest: ~/.taskrc
    mode: 0644
    owner: jim
    group: jim
    backup: yes

# GTD for TaskWarrior
# https://cs-syd.eu/posts/2015-06-21-gtd-with-taskwarrior-part-2-collection
- name: Create GTD aliases for taskwarrior
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK - taskwarrior"
    path: ~/.bashrc
    block: |
      alias in='task add +in'
