- name: Install Pass
  apt:
    name:
      - pass
    state: latest
    update_cache: true
  become: true

# TODO: Only copy over .password_store if it doesn't exist

# TODO: Retrieve .password-store location from vars file
- name: Copy .password-store.git from backup
  copy:
    src: "/media/jim/GOKIT/password-store.git"
    dest: "{{ lookup('env', 'HOME') }}/.password-store/"
    mode: 0755
    backup: yes

- name: Convert .password-store.git to a full git repo
  script: convert_pass_repo.sh

- name: Set PASSWORD_STORE_DIR in .bashrc
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK - level0 - PASS"
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    block: |
      export PASSWORD_STORE_DIR="/home/jim/.password-store"

      bah () {
          if [ $PASSWORD_STORE_DIR == "/home/jim/.password-store" ]; then
              echo "Switching to BAH password stare"
              export PASSWORD_STORE_DIR="/home/jim/.bah/.password-store"
          else
              echo "Switching to main password stare"
              export PASSWORD_STORE_DIR="/home/jim/.password-store"
          fi
      }

      source /usr/share/bash-completion/completions/pass
