- name: Install Pass
  apt:
    name:
      - pass
    state: latest
  become: true

# TODO: Only copy over .password_store if it doesn't exist

# TODO: Retrieve .password-store location from vars file
- name: Copy .password-store from backup
  copy:
    src: "/media/jim/GOKIT/.password-store"
    dest: "{{ lookup('env', 'HOME') }}"
    mode: 0755
    backup: yes

- name: Set PASSWORD_STORE_DIR in .bashrc
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK - level0 - PASS"
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    block: |
      export PASSWORD_STORE_DIR="/home/jim/.password-store"
      source /usr/share/bash-completion/completions/pass

- name: Create cron job for updating pass
  cron:
    name: "pass sync"
    minute: "*/15"
    job: "/usr/bin/pass sync &>/dev/null"
