- name: Install latest emacs
  apt:
    name:
      - emacs
      # holy smokes:
      # https://emacs.stackexchange.com/questions/7238/info-file-emacs-does-not-exist
      - emacs-common-non-dfsg
    state: latest
  become: true

- name: Ensure ~/.emacs.d folder is present
  file:
    dest: ~/.emacs.d
    state: directory
    mode: 0700

- name: Install ~/.emacs.d/init.el
  copy:
    src: emacs/init.el
    dest: ~/.emacs.d/init.el
    mode: 0644
    backup: yes
