- name: Add .bashrc aliases
  blockinfile:
     marker: "# {mark} ANSIBLE MANAGED BLOCK - .bashrc"
     path: /home/vagrant/.bashrc
     block: |
         alias h='cd $(pwd | cut -d '/' -f 1-5); pwd'  # Move to head (top) folder of git projects (bit hacky)
