- name: Ensure mapped folder exists
  file:
    path: ~/mapped
    state: directory
    mode: 0700

- name: Add .bashrc aliases
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK - .bashrc"
    path: ~/.bashrc
    block: |
      alias h='cd $(pwd | cut -d '/' -f 1-5); pwd'  # Move to head (top) folder of git projects (bit hacky)

      # History
      # https://www.gnu.org/software/bash/manual/html_node/Bash-History-Builtins.html
      shopt -s histappend   # append to history, don't overwrite it
      export HISTFILE="~/mapped/bash_history"
      export HISTCONTROL=   # allow duplicate entries
      export HISTSIZE=      # unlimited history
      export HISTFILESIZE=  # unlimited history
      export HISTTIMEFORMAT="%F %T: "
      export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"  # Append command to history after it completes (use `history -r` to reload history in other sessions)

      # In history file, note when new session is started
      # https://stackoverflow.com/questions/911168/how-to-detect-if-my-shell-script-is-running-through-a-pipe
      if [ -t 1 ]; then echo -e "#$(date +%s)\n#--- new session ---" >> $HISTFILE; fi
