# https://docs.docker.com/install/linux/docker-ce/centos/
- block:
    - name: Install docker dependencies
      dnf:
        name: ['device-mapper-persistent-data', 'lvm2']
        state: latest

    - name: Add (stable) docker repo
      command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        warn: false  # ansible's dnf module doesn't seem to support adding repos

    - name: Install docker
      # --nobest required in order to install containerd.io >= 1.2.2-3
      # error: https://gist.github.com/jladdjr/a85921880790dcade9c2548e8f1cd3d9
      shell: dnf install -y docker-ce --nobest
      args:
        warn: false  # dnf module does not seem to support --nobest option

    - name: Enable docker service
      systemd:
        name: docker
        enabled: yes

    - name: Start docker service
      systemd:
        name: docker
        state: started

    - name: Run hello world container
      command: docker run hello-world

    # https://docs.docker.com/compose/install/
    # To ensure you have the latest version, check the Compose repository release page on GitHub:
    # https://github.com/docker/compose/releases (up-to-date as of 6/30/20)
    - name: Install docker-compose
      shell: curl -L https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/bin/docker-compose
      args:
        warn: false  # use shell module instead of get_url in order to use `$()` in command

    - name: Make docker-compose executable
      file:
        dest: /usr/bin/docker-compose
        mode: 0755
  become: true

# https://techoverflow.net/2017/03/01/solving-docker-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket/
# May want to use user module instead: https://docs.ansible.com/ansible/latest/modules/user_module.html
- name: Get current user
  shell: whoami
  register: shell

- name: Add {{ shell.stdout }} to docker group (so docker can be run w/out sudo)
  shell: usermod -a -G docker {{ shell.stdout }}
  become: true
