- name: Install latest emacs
  dnf:
    name: emacs
    state: latest
  become: true

- name: Install .spaceemacs dot file
  copy:
    scr: dot_spacemacs
    dest: "{{ lookup('env', 'HOME') }}"/.spacemacs
    mode: 644
