# https://cloud.google.com/sdk/docs/quickstart-linux (select Fedora tab)

- name: Add gcloud repo
  copy:
    src: gcloud_repo
    dest: /etc/yum.repos.d/google-cloud-sdk.repo
  become: true
  tags: gcloud

- name: get google-cloud-sdk
  dnf:
    name: google-cloud-sdk
    state: latest
  become: true
  tags: gcloud

- name: Set default gcloud project
  command: gcloud config set project ansible-tower-engineering
  tags: gcloud
