- name: Remove existing git
  yum:
    name: git
    state: absent
  become: true

- name: Install latest git
  yum:
    name: git2u
    state: latest
  become: true

- name: Copy .gitconfig
  copy:
    src: .gitconfig
    dest: ~
    mode: 0755

- name: Create .gitignore_global
  copy:
    src: dot_gitignore_global
    dest: ~/.gitignore_global
    mode: 0600

- name: Configure git to use global .gitignore file
  shell: git config --global core.excludesfile ~/.gitignore_global
  args:
    executable: /bin/bash
