- import_tasks: bash.yml
  tags: bash

- import_tasks: ag.yml
  tags: [ag]

- import_tasks: fzf.yml
  tags: [fzf]

- import_tasks: git.yml
  tags: git

- import_tasks: tmux.yml
  tags: tmux

- import_tasks: tmux-focus-events.yml
  tags: [tmux-focus-events]

- import_tasks: docker.yml
  tags: docker

- import_tasks: podman.yml
  tags: podman

- import_tasks: gcloud.yml
  tags: gcloud

- import_tasks: nodejs.yml
  tags: nodejs

- import_tasks: misc.yml
  tags: misc-devtools
