- import_tasks: bash.yml
  tags: bash

- import_tasks: vim.yml
  tags: vim

# ag, fzf, and NERDTree require vim / pathogen to be installed first
- import_tasks: ag.yml
  tags: ag

- import_tasks: fzf.yml
  tags: fzf

- import_tasks: nerdtree.yml
  tags: nerdtree

- import_tasks: git.yml
  tags: git

- import_tasks: tmux.yml
  tags: tmux

- import_tasks: docker.yml
  tags: docker

- import_tasks: gcloud.yml
  tags: gcloud

- import_tasks: nodejs.yml
  tags: nodejs

- import_tasks: misc.yml
  tags: misc-devtools
