- name: Install rhubarb vim plugin
  git:
    repo: https://github.com/tpope/vim-rhubarb.git
    dest: "~/.vim/bundle/rhubarb.vim"
  tags: rhubarb

- name: Ensure ~/.netrc exists
  file:
    state: touch
    path: ~/.netrc
    mode: 0600
  tags: rhubarb

- name: Update ~/.netrc with github creds
  lineinfile:
    path: ~/.netrc
    line: "machine api.github.com login {{ rhubarb_github_username }} password {{ rhubarb_github_token }}"
    regexp: "^machine api.github.com login {{ rhubarb_github_username }} .*$"
  no_log: true
  tags: rhubarb

- name: Ensure /var/mapped/bin folder exists
  file:
    path: /var/mapped/bin
    state: directory
    mode: 0755
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  tags: rhubarb

- name: Copy open_link.sh to mapped folder
  copy:
    src: rhubarb/open_link.sh
    dest: /var/mapped/bin
    mode: 0755
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  tags: rhubarb

- name: Ensure /usr/bin/jim folder exists
  file:
    path: /usr/bin/jim
    state: directory
    mode: 0755
    owner: root
    group: root
  become: true
  tags: rhubarb

- name: Add /usr/bin/jim folder to PATH
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=/usr/bin/jim:$PATH'
    state: present
  tags: rhubarb

- name: Copy open_link_on_host script to /usr/bin/jim
  copy:
    src: rhubarb/open_link_on_host
    dest: /usr/bin/jim
    mode: 0755
    owner: root
    group: root
  become: true
  tags: rhubarb

- name: Configure netrw to open links with open_link_on_host
  lineinfile:
    path: ~/.vimrc
    line: let g:netrw_browsex_viewer="open_link_on_host"
    regexp: "^let g:netrw_browsex_viewer.*$"
  tags: rhubarb

- name: Add rhubarb key bindings to vimrc
  blockinfile:
    path: ~/.vimrc
    block: |
      " rhubarb
      nmap <Leader>g :Gbrowse<CR>
      vmap g :Gbrowse<CR>
    marker: '" {mark} ANSIBLE MANAGED BLOCK - rhubarb'
  tags: rhubarb
