- name: Install syntastic vim plugin
  git:
    repo: https://github.com/vim-syntastic/syntastic.git
    dest: "~/.vim/bundle/syntastic.vim"
  tags: [syntastic]

- name: Add vim configuration for syntastic
  blockinfile:
    path: ~/.vimrc
    block: |
      " Syntastic
      set statusline+=%#warningmsg#
      set statusline+=%{SyntasticStatuslineFlag()}
      set statusline+=%*
      
      let g:syntastic_always_populate_loc_list = 1
      let g:syntastic_auto_loc_list = 1
      let g:syntastic_check_on_open = 1
      let g:syntastic_check_on_wq = 0
    marker: '" {mark} ANSIBLE MANAGED BLOCK - Syntastic'
