- name: Install syntastic vim plugin
  git:
    repo: https://github.com/vim-syntastic/syntastic.git
    dest: "~/.vim/bundle/syntastic.vim"
  tags: [syntastic]

- name: Add vim configuration for syntastic
  blockinfile:
    path: ~/.vimrc
    block: |
      " Syntastic
      " In order for Syntastic to correctly show errors
      " make sure that flake8 is kept up-to-date!
      let g:syntastic_always_populate_loc_list = 1
      let g:syntastic_auto_loc_list = 1
      let g:syntastic_check_on_open = 1
      let g:syntastic_check_on_wq = 0
      nmap <Leader>r :SyntasticReset<CR>:f<CR>
    marker: '" {mark} ANSIBLE MANAGED BLOCK - Syntastic'
