# https://gist.github.com/pierreprinetti/86fbcd28e5cc1b3e0b9b762e4c12fad2
- name: Remove old tmux
  yum:
      name: tmux
      state: absent
  become: true
- name: Install latest tmux
  yum:
      name: tmux2u
      state: latest
  become: true
- name: Copy .tmux.conf
  copy:
      src: .tmux.conf
      dest: /home/vagrant
      mode: 0755
