- name: Install latest tmux
  dnf:
    name: tmux
    state: latest
  become: true

- name: Copy .tmux.conf
  copy:
    src: tmux.conf
    dest: ~/.tmux.conf
    mode: 0755

- name: Run tmux in new shells
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK - tmux"
    path: ~/.bash_profile
    block: |
      if [ -z "$TMUX" ]; then
          tmux
      fi

- name: Create git plugin directory
  file:
    state: directory
    path: ~/.tmux/plugins
    mode: 0755

- name: Install tmux-resurrect
  git:
    dest: ~/.tmux/plugins
    repo: http://github.com/tmux-plugins/tmux-resurrect.git
    accept_hostkey: yes

- name: Source resurrect.tmux
  lineinfile:
    path: ~/.tmux.conf
    line: run-shell ~/.tmux/plugins/resurrect.tmux

- name: When opening new shell, auto-join existing tmux sessions (or create new one)
  blockinfile:
    path: ~/.bash_profile
    block: |
      tmux list-sessions > /dev/null 2>&1
      if [ $? -eq 0 ]; then
          if [ -z "$TMUX" ]; then
              tmux attach
          fi
      else
          tmux
      fi
    marker: "# {mark} ANSIBLE MANAGED BLOCK - tmux"
