# https://gist.github.com/pierreprinetti/86fbcd28e5cc1b3e0b9b762e4c12fad2
- name: Remove old tmux
  yum:
    name: tmux
    state: absent
  become: true

- name: Install latest tmux
  yum:
    name: tmux2u
    state: latest
  become: true

- name: Copy .tmux.conf
  copy:
    src: tmux.conf
    dest: /home/vagrant/.tmux.conf
    mode: 0755

- name: Run tmux in new shells
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK - tmux"
    path: /home/vagrant/.bash_profile
    block: |
      if [ -z "$TMUX" ]; then
          tmux
      fi

- name: Create git plugin directory
  file:
    state: directory
    path: /home/vagrant/.tmux/plugins
    mode: 0755

- name: Install tmux-resurrect
  git:
    dest: /home/vagrant/.tmux/plugins
    repo: git@github.com:tmux-plugins/tmux-resurrect
    accept_hostkey: yes

- name: Source resurrect.tmux
  lineinfile:
    path: /home/vagrant/.tmux.conf
    line: run-shell /home/vagrant/.tmux/plugins/resurrect.tmux

- name: When opening new shell, auto-join existing tmux sessions (or create new one)
  blockinfile:
    path: /home/vagrant/.bash_profile
    block: |
      tmux list-sessions > /dev/null 2>&1
      if [ $? -eq 0 ]; then
          if [ -z "$TMUX" ]; then
              tmux attach
          fi
      else
          tmux
      fi
    marker: "# {mark} ANSIBLE MANAGED BLOCK - tmux"
