- name: Install vim
  yum:
    name: vim
    state: latest
  become: true

- name: Replace vi with vim
  file:
    src: /bin/vim
    dest: /bin/vi
    state: link
    force: yes
  become: true

- include_tasks: vim_config.yml
  loop:
    - ~
    - /root
  loop_control:
    loop_var: home_dir
