- name: Install vim
  yum:
    name: vim
    state: latest
  become: true

- name: Replace vi with vim
  file:
    src: /bin/vim
    dest: /bin/vi
    state: link
    force: yes
  become: true

- include_tasks: vim_config.yml
  loop:
    - "{{ ansible_user_dir }}"
    - /root
  loop_control:
    loop_var: home_dir

- name: periodically renice vim commands
  cron:
    name: renice vim
    minute: "*/5"
    job: renice -17 $(pgrep vim)
  become: true
