- hosts: all
  roles:
    - { role: docker, tags: docker }
    - { role: python, tags: python }
    - { role: fzf, tags: fzf }

- hosts: all
  tasks:
    - name: Install specialized tools
      apt:
        name:
          - clusterssh  # provides cssh
          # Manually install VirtualBox by downloading deb.
          # (package is only included in sid package repo)
          # https://www.oracle.com/virtualization/technologies/vm/downloads/virtualbox-downloads.html
          - vagrant
        state: latest
      become: true
