# https://docs.docker.com/install/linux/docker-ce/centos/
- name: Install required packages
  yum:
      name: "{{ item }}"
      state: latest
  with_items:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
  become: true
- name: Add (stable) docker repo
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  become: true
- name: Install docker
  yum:
      name: docker-ce
      state: latest
  become: true
- name: Enable docker service
  systemd:
      name: docker
      enabled: yes
  become: true
- name: Start docker service
  systemd:
      name: docker
      state: started
  become: true
- name: Run hello world container
  command: docker run hello-world
  become: true
# https://docs.docker.com/compose/install/
# To ensure you have the latest version, check the Compose repository release page on GitHub:
# https://github.com/docker/compose/releases (up-to-date as of 4/16/2018)
- name: Install docker-compose
  shell: curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/bin/docker-compose
  become: true
- name: Make docker-compose executable
  file:
      dest: /usr/bin/docker-compose
      mode: 0755
  become: true
