#!/bin/bash

ledger () {
    # Define the directory and file
    directory="/home/steph/.lock"
    file="ledger"
    file_path="$directory/$file"

    # Check if the file exists
    if [ -f "$file_path" ]; then
        echo "Ledger already open on $(cat $file_path)"
	notify-send -i /usr/share/icons/hicolor/symbolic/apps/org.gnome.Calendar-symbolic.svg "Ledger already open on $(cat $file_path)"
        exit 0
    else
        # Create the file with the system's hostname as the content
        hostname > $file_path

        counter=1
	cd ~/ledger
        # echo "Skipping git pull"
        git pull &>/dev/null || true
        /usr/bin/emacsclient -c -a emacs journal.ledger &>/dev/null

        # determine if any changes were made
        git diff --exit-code
        if [ "$?" -eq 0 ]; then
          rm -f $file_path
          exit 0
        fi

        git add -u >/dev/null
        git commit -m "toil: `whoami` update" >/dev/null
        # determine if git's pre-commit script was successful
        if [ $? -ne 0 ]; then
            rm -f $file_path
            return 1
        fi

        echo "Skipping git push"
        # TODO (revert): skip git push because you can't push to
        # a repository that has the same branch checked out
        # because it causes the local checkout to get out of sync
        # git push >/dev/null

        # attempt to have holodeck pull changes
        # but don't consider this a failure if
        # it doesn't work
        #ssh jim@holodeck.home.arpa 'cd ~/ledger; git pull' || true
        rm -f $file_path
    fi
}

ledger
rc=$?

while [ $rc -ne 0 ] && [ $counter -lt 3 ]; do
  ledger
  rc=$?
  ((counter++))
done
