\input texinfo
@settitle Jim Manual 1.0

@copying
Jim Manual 1.0

Copyright @copyright{} 2023 Jim Ladd
@end copying

@titlepage
@title Jim Manual
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@node Top
@top Jim Manual

This manual provides instructions for manually configuring
the following applications in a Debian 12 environment:

- foo
- barr

@menu
* Configuring Foo::    How to configure Foo
* Index::              Index
@end menu


@node Configuring Foo
@chapter First part of configuring Foo

@cindex foo, config
This is the first chapter on configuring Foo
@cindex index entry, another

Here is a numbered list.

@enumerate
@item
This is the first item.

@item
This is the second item.
@end enumerate



@node First Section
@section First Section

First section of first chapter.


@node Second Section
@section Second Section

Second section of first chapter.


@node Index
@unnumbered Index

@printindex cp

@bye
