- name: Install plover (on non-vm machines)
  block:
  # apt package is down-level, so install appimage from github (12/28/2021)
  - name: Install plover on bare-metal Debian machines
    get_url:
      # stable as of 12/28/2021
      url: https://github.com/openstenoproject/plover/releases/download/continuous/plover-4.0.0.dev10+120.g4394ef1-x86_64.AppImage
      dest: /usr/local/bin/plover
      owner: jim
      group: jim
      mode: 0755
    become: true
    when: hostvars[inventory_hostname].ansible_distribution == 'Debian' and hostvars[inventory_hostname].ansible_architecture.find('arm') == -1

  # TODO: Install plover on mac and raspberry pi's

  - name: "Download dictionaries (beware: overwrites local changes!)"
    git:
      repo: 'git@github.com:jladdjr/steno-reboot.git'
      dest: ~/steno-reboot
      update: yes
      force: yes

  - name: Ensure ~/.local/share/plover exists
    file:
      state: directory
      path: ~/.local/share/plover
      mode: 0755

  # https://plover.readthedocs.io/en/latest/api/oslayer_config.html#plover.oslayer.config.CONFIG_DIR
  - name: Install plover.cfg
    template:
      src: plover/plover.cfg.j2
      dest: ~/.local/share/plover/plover.cfg

  - name: Add user to dialout group on Debian machines
    shell: "usermod -a -G dialout {{ ansible_user|default('jim') }}"
    become: true
    when: hostvars[inventory_hostname].ansible_distribution == 'Debian'

  # https://plover.readthedocs.io/en/4.0.0-dev8/cli_reference.html#plugin-installer
  - name: Add support for python dictionaries on bare-metal Debian machines
    shell: /usr/local/bin/plover -s plover_plugins install plover-python-dictionary
    when: hostvars[inventory_hostname].ansible_distribution == 'Debian' and hostvars[inventory_hostname].ansible_architecture.find('arm') == -1

  # TODO: Add support for python dictionaries on mac and raspberry pi's

  when: hostvars[inventory_hostname].ansible_virtualization_type != 'virtualbox'
