# Use interactive prompt to locate backup files
- hosts: all
  vars_prompt:
    - name: pass_backup_dir
      prompt: Location of pass backup dir?
      default: "/media/jim/GOKIT/.password-store"

- hosts: all
  tasks:
    - name: Install essential packages
      apt:
        name:
          - vim
          - info
          - locate
          - bc
          - screen
          - htop
          - strace
          - apt-file
          - e2fsprogs
          - strace
          - fd-find
          - calibre
          - rsync
        state: latest
      become: true

- hosts: all
  roles:
    - { role: bash, tags: bash }
    - { role: git, tags: git }
    - { role: pass, tags: pass }

