- hosts: all
  tasks:
    - name: Install essential packages
      apt:
        name:
          - apt-file
          - bc
          - calibre
          - e2fsprogs
          - fd-find
          - htop
          - info
          - locate
          - openssh-server
          - rsync
          - screen
          - strace
          - strace
          - vim
          - wget
        state: latest
        update_cache: true
      become: true

- hosts: all
  roles:
    - { role: bash, tags: bash }
    - { role: git, tags: git }
    - { role: pass, tags: pass }
    - { role: tmux, tags: tmux}

