#!/bin/bash

guest_mapped="/var/mapped"
host_mapped="/Users/jim/Vagrant/mapped"
path=${1/$guest_mapped/$host_mapped}

HOST=$(netstat -rn | grep '^0.0.0.0' | awk '{print $2}')
ssh jim@${HOST} /Users/jim/Vagrant/mapped/bin/open_link.sh \"$path\"

if [[ $path != $1 ]]; then
    # Wait until explicitly told to close, otherwise
    # browser may attempt to read file that has been cleaned up
    read -p "Press [Enter] when finished viewing page..."
fi
