- hosts: all
  roles:
    - { role: nerdfont, tags: nerdfont }
    - { role: starship, tags: starship }

- hosts: all
  tasks:
    - name: Install PDF viewers
      apt:
        name:
          # okular's annotation / freehand line drawing
          # lets you draw your signature onto a pdf and save
          # https://www.reddit.com/r/kde/comments/s2aqn0/tip_add_your_signature_with_okular_to_a_pdf_sign/
          - okular
          - zathura
        state: latest
        update_cache: true
      become: true

# TODO: Apply script as part of role task
#
# watson_stars.sh
#
# N=$(watson report -c -d -j | jq '.time / 3600 | floor')
#
# if [[ "$N" == 8 ]]; then
#   printf "done!"
#   exit
# fi
#
# M=$((N + 1))
#
# printf '['
# if [[ "$N" != 0 ]]; then
#   printf "*%.0s" $(seq 1 $N)
#   printf "_%.0s" $(seq $M 8)
# else
#   printf "________"
# fi
# printf ']'

# In .tmux.conf
#
# set -g status-right '#(/path/to/watson_stars.sh) .. <existing status content>'
