- hosts: all
  roles:
    - { role: borg, tags: borg }
    - { role: emacs, tags: emacs }
    - { role: pass, tags: pass }
    # - { role: joplin, tags: joplin }
    - { role: syncthing, tags: syncthing }

- hosts: all
  tasks:
    - name: Install core tools
      apt:
        name:
          - mailutils   # provides mail (essential for reading cron mail)
          - dnsutils    # provides dig (for getting DNS record info)
          - traceroute
          - lm-sensors  # provides sensors, for checking machine temps
          - jdupes      # for general de-duplication
          - ffmpeg      # video conversion
          - dos2unix
        state: latest
      become: true
