all:
	ansible-playbook -i inventory provision.yml

# see also fzf (which enables ctrl-t hotkey for searching for files)
ag:
	ansible-playbook -i inventory --tags ag provision.yml

bash:
	ansible-playbook -i inventory --tags bash provision.yml

brave:
	ansible-playbook -i inventory --tags brave provision.yml

creature_comforts:
	ansible-playbook -i inventory --tags creature_comforts provision.yml

emacs:
	ansible-playbook -i inventory --tags emacs provision.yml

fzf:
	ansible-playbook -i inventory --tags fzf provision.yml

general_dev_tools:
	ansible-playbook -i inventory --tags general_dev_tools provision.yml

git:
	ansible-playbook -i inventory --tags git provision.yml

i3:
	ansible-playbook -i inventory --tags redshift,i3,system76 provision.yml

joplin:
	ansible-playbook -i inventory --tags joplin provision.yml

pass:
	ansible-playbook -i inventory --tags pass provision.yml

pass_sync:
	ansible-playbook -i inventory --tags pass_sync provision.yml

redshift:
	ansible-playbook -i inventory --tags redshift provision.yml

system-repos:
	ansible-playbook -i inventory --tags system_repos provision.yml

system76:
	ansible-playbook -i inventory --tags system76 provision.yml

tmux:
	ansible-playbook -i inventory --tags tmux provision.yml

xmodmap:
	ansible-playbook -i inventory --tags xmodmap provision.yml
