---
- hosts: jim
  roles:
    - { role: system, tags: system }
    - { role: dev-tools, tags: dev-tools }
    - { role: creature_comforts, tags: creature_comforts }
    - { role: apps, tags: apps }

# machine-dependent tasks
- hosts: local
  tasks:
    - include_role:
        name: system76
      when: "'System76' in ansible_facts.chassis_vendor"
      tags: system76
